ets-berkeley-edu/nessie

- consoler.py
- nessie/externals/redshift.py
- tests/test_externals/test_redshift.py
- tests/util.py
https://jira.ets.berkeley.edu/jira/browse/LA-319
After an unexpectedly long detour into getting pytest to see the app logs, here's a super-simple Redshift connection. Still to come: machinery for running automated tests against a real Redshift.
> LA-319 Basic Redshift client; add consoler

- README.md
- config/default.py
- config/testext.py
- consoler.py
- nessie/externals/redshift.py
- tests/conftest.py
- tests/test_externals/test_redshift.py
https://jira.ets.berkeley.edu/jira/browse/LA-326
Since these external tests require access to private configs (and may be slow), they don't run under Travis. They could conceivably be incorporated into a CodePipeline run, as CalCentral/Junction does on Bamboo.
> LA-326 Testext environment support; expanded Redshift code and tests

- config/default.py
- fixtures/canvas_data_file_sync.json
- nessie/externals/canvas_data.py
- nessie/lib/mockingbird.py
- nessie/lib/util.py
- tests/test_externals/test_canvas_data.py
https://jira.ets.berkeley.edu/jira/browse/LA-320
`nessie.lib.mockingbird` and `nessie.lib.util` are straight copy-paste from their BOAC equivalents. At some point, if it looks like we're going to be keeping around a stable of Python projects, we might look at extracting shared dependencies into their own repo.
> LA-320 Canvas Data API client, test coverage

- config/default.py
- fixtures/dispatch_create_canvas_schema.json
- nessie/lib/dispatcher.py
- nessie/lib/http.py
- nessie/lib/mockingbird.py
- tests/test_lib/test_dispatcher.py
https://jira.ets.berkeley.edu/jira/browse/LA-338
Library code supporting non-GET HTTP methods can be copied back to BOAC.
> LA-338 Master-to-worker job dispatch

- nessie/lib/mockingbird.py
https://jira.ets.berkeley.edu/jira/browse/LA-338
Follow-up to #6; BOAC version is ets-berkeley-edu/boac#511.
> LA-338 Follow-up: no-op mock must take no-op kwargs

- .gitignore
- buildspec.yml
- scripts/create-build-summary.sh
https://jira.ets.berkeley.edu/jira/browse/LA-381
https://jira.ets.berkeley.edu/jira/browse/LA-392
* `code-build-nessie-service-role` will be created in CodeBuild setup (coming soon)
* Regarding build-summary, `gitCommit` in /api/version is useful.
> LA-381, buildspec and build-summary file for /api/version

- .ebextensions/00_ami.config
https://jira.ets.berkeley.edu/jira/browse/LA-380
Thanks to Darlene, I did nothing more than grab the `arn` from AWS Certificate Manager.
> LA-380, Nessie gets aws:elbv2:listener:443:SSLCertificateArns

- config/default.py
- config/testext.py
- nessie/api/job_controller.py
- nessie/externals/redshift.py
- nessie/jobs/background_job.py
- nessie/jobs/create_sis_schema.py
- nessie/jobs/generate_intermediate_tables.py
- nessie/sql_templates/create_boac_schema.template.sql
- nessie/sql_templates/create_intermediate_schema.template.sql
- nessie/sql_templates/create_sis_schema.template.sql
- tests/test_api/test_job_controller.py
https://jira.ets.berkeley.edu/jira/browse/LA-397
Three commits because the work comes in three parts:
1. Create an external schema in Redshift for our SIS data snapshots;
2. Generate some persistent internal tables to bring together Canvas and SIS data. (I too am suspicious of creating schemata all over the place, but we did seem to need at least one more for generally applicable internal tables that have nothing to do with BOAC as such.)
3. Take some load off BOAC-specific table creation by allowing it to pull data from the intermediate tables, including SIS enrollment status. Queries from the BOAC side can then filter their result sets by enrollment status if desired.
> LA-397 Make SIS enrollment status available to loch queries

- .ebextensions/00_ami.config
https://jira.ets.berkeley.edu/jira/browse/LA-401
As seen in BOAC: https://github.com/ets-berkeley-edu/boac/blob/master/.ebextensions/00_ami.config
> LA-401, default listener (port 80) is enabled, but will redirect to 443 per Apache config

- config/default.py
- nessie/factory.py
- nessie/jobs/scheduling.py
- requirements.txt
https://jira.ets.berkeley.edu/jira/browse/LA-318
Note that configs defined here will constitute our first split between master and worker environments: only master should wield the power of JOB_SCHEDULING_ENABLED.
> LA-318 Support job scheduling from config files

- .ebextensions/00_ami.config
https://jira.ets.berkeley.edu/jira/browse/LA-415
The niceness of S3 logs is outweighed by the nastiness of instances restarting every hour.
> LA-415 Disable log rotation to S3

- .travis.yml
- README.md
- config/default.py
- config/test.py
- config/testext.py
- nessie/api/job_controller.py
- nessie/externals/redshift.py
- nessie/externals/s3.py
- nessie/jobs/background_job.py
- nessie/jobs/sync_canvas_snapshots.py
- nessie/jobs/sync_file_to_s3.py
- nessie/lib/metadata.py
- nessie/sql_templates/create_metadata_schema.template.sql
- requirements.txt
- tests/conftest.py
- tests/test_externals/test_redshift.py
- tests/test_externals/test_s3.py
- tests/test_jobs/test_sync_canvas_snapshots.py
- tests/test_jobs/test_sync_file_to_s3.py
https://jira.ets.berkeley.edu/jira/browse/LA-323
Here's a first stab at a coordinated metadata store. We have two tables: one to store results per sync job, per file, and one to serve as an inventory of actual files currently in S3.
Much of this PR is supporting architecture for test coverage. We use a local Postgres to mock out the Redshift interface; that database needs to be created for local test runs as described in the README. Let's see what Travis thinks...
> LA-323 Centralized metadata for distributed Canvas sync jobs

- fixtures/sonnet_xlv.html
- tests/test_jobs/test_sync_file_to_s3.py
https://jira.ets.berkeley.edu/jira/browse/LA-443
Moto, our mock AWS library, prefers HTTP mocks to come by way of `responses` rather than `httpretty`. It would be nice to get all our HTTP mocks consistent, but this stops the intermittent failure for now.
> LA-443 Plug intermittent test failure with fixture

- nessie/jobs/background_job.py
- nessie/jobs/create_canvas_schema.py
- nessie/jobs/create_sis_schema.py
https://jira.ets.berkeley.edu/jira/browse/LA-428
If anything is amiss, returning `False` from these jobs will abort subsequent jobs and leave BOAC's materialized views intact.
> LA-428 Verify external schemas after drop and recreation

- nessie/sql_templates/create_boac_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-917
When that happens, we still need to return `last_activity_at` and `sis_enrollment_status`.
> BOAC-917 A student without scores might lack a course_score_fact row

- nessie/api/job_controller.py
- nessie/jobs/scheduling.py
- tests/test_api/test_job_controller.py
https://jira.ets.berkeley.edu/jira/browse/NS-89
It's no `crontab -l`, but I hope it serves. A global scheduler object gives us something to grab when needed, though it probably won't be enough to prevent multiple scheduler instances in different processes. @raydavis's suggestion in https://jira.ets.berkeley.edu/jira/browse/NS-107 of a Postgres advisory lock seems like a good way to handle it.
> NS-89 Job schedule API endpoint

- nessie/api/job_controller.py
- nessie/api/schedule_controller.py
- nessie/jobs/scheduling.py
- nessie/routes.py
- tests/test_api/test_job_controller.py
- tests/test_api/test_schedule_controller.py
- tests/util.py
https://jira.ets.berkeley.edu/jira/browse/NS-89
Example usage:
`curl -u username:password -d '{"hour": 12, "minute": "30"}' https://app-master-prod.ets-berkeley-nessie.net/api/schedule/job_sync_canvas_snapshots`
To turn the job off:
`curl -u username:password -d '{}' http://app-master-prod.ets-berkeley-nessie.net/api/schedule/job_sync_canvas_snapshots`
> NS-89 POST endpoint to manage job schedules

- config/default.py
- nessie/api/job_controller.py
- nessie/externals/redshift.py
- nessie/jobs/background_job.py
- nessie/jobs/create_asc_schema.py
- nessie/jobs/import_asc_athletes.py
- nessie/lib/db.py
- nessie/sql_templates/create_asc_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-82
* `get_psycopg_cursor` is now a shared db util because _psycopg2_ is necessary to run SQL: `COPY (SELECT ROW_TO_JSON...)` during ASC import.
* `create_asc_schema.template.sql` is unfinished; verifying Redshift schema creation is next step.
> NS-82, create_asc_schema uses JSON files uploaded to S3 by ASC import job

- nessie/externals/asc_athletes_api.py
- nessie/jobs/import_asc_athletes.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-982
"API returned zero results" is wrong if ASC API is down.
> BOAC-982, if ASC API is down then log a proper error message

- config/default.py
- nessie/externals/boac.py
- nessie/jobs/refresh_boac_cache.py
- nessie/jobs/scheduling.py
- tests/test_api/test_schedule_controller.py
https://jira.ets.berkeley.edu/jira/browse/NS-81
If this PR passes muster, there are a couple of operational steps associated with deploy:
- Add BOAC_API_KEY, BOAC_CACHE_REFRESH_URL, and JOB_REFRESH_BOAC_CACHE keys to nessie-master-dev config;
- Remove the corresponding cronjob on junction-dev so that Nessie can take over.
> NS-81 Job to kick off BOAC cache refresh

- config/default.py
- nessie/jobs/background_job.py
- nessie/jobs/generate_merged_profiles.py
- nessie/lib/berkeley.py
- nessie/merged/sis_profile.py
- nessie/sql_templates/create_student_schema.template.sql
- tests/test_lib/test_berkeley.py
- tests/test_lib/test_util.py
- tests/test_merged/test_sis_profile.py
https://jira.ets.berkeley.edu/jira/browse/NS-131
Let's see how this flies. We loop through all sids in our Calnet stash, create merged profiles and output results to three internal Redshift tables: one with a big JSON payload and two others with extracted queryable values. (I expect that these queries will run somewhat slow compared to Postgres, but our future selves can sort that out.)
Results for our athlete population can be inspected in nessie_dev under the student_pk_test schema.
If this seems workable, the next steps would be to do something similar with student enrollment terms and try to fill out the skimpy test coverage.
> NS-131 Background job to generate student profile tables in Redshift

- config/default.py
- config/testext.py
- nessie/jobs/background_job.py
- nessie/jobs/create_asc_schema.py
- nessie/sql_templates/create_asc_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-133
Too many schemas? Check. No tests? Check. Outstanding TODOs? Check. But since this isn't yet a scheduled job, it's probably better to submit as is than leave it to languish on a working branch.
`student_profiles` contains precomposed JSON for quick serving.
`students` contains index columns suitable for querying on ASC attributes.
Output available for inspection under nessie_dev/boac_advising_asc_pk_test.
> NS-133 Internal schema containing ASC athletic profiles

- nessie/externals/sis_degree_progress_api.py
- nessie/externals/sis_enrollments_api.py
- nessie/jobs/background_job.py
- nessie/jobs/create_asc_schema.py
- nessie/jobs/create_coe_schema.py
- nessie/jobs/generate_boac_analytics.py
- nessie/jobs/generate_intermediate_tables.py
- nessie/jobs/generate_merged_student_feeds.py
- nessie/jobs/import_degree_progress.py
- nessie/jobs/import_sis_enrollments_api.py
- nessie/jobs/import_sis_student_api.py
- nessie/jobs/resync_canvas_snapshots.py
- nessie/jobs/sync_canvas_snapshots.py
- nessie/lib/http.py
- nessie/lib/metadata.py
- nessie/merged/sis_profile.py
- nessie/sql_templates/create_metadata_schema.template.sql
- tests/conftest.py
- tests/test_jobs/test_resync_canvas_snapshots.py
- tests/test_jobs/test_sync_canvas_snapshots.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1033
- Use a staging table on API loops so that today's failed retrieval doesn't wipe out yesterday's success;
- Don't log 404s as errors for API loops which return 404s in the normal course of business;
- Fix a dumb bug that caused merged profile generation to fail if degree progress was missing;
- Both succeeded and failed jobs can return a status string which will be stored in the metadata table.
> BOAC-1033 Better background job logging, failure tolerance

- nessie/api/job_controller.py
- nessie/factory.py
- nessie/jobs/create_metadata_schema.py
- nessie/jobs/create_student_schema.py
- nessie/jobs/generate_asc_profiles.py
- nessie/jobs/scheduling.py
- nessie/sql_templates/create_asc_schema.template.sql
- nessie/sql_templates/create_metadata_schema.template.sql
- nessie/sql_templates/create_student_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-168
In addition to startup check,
- Get the components of API-triggered chained jobs in alignment with scheduled jobs;
- Rename the old CreateAscSchema job (which no longer creates the ASC schema) to GenerateAscProfiles (which is what it does).
Because of the job rename, this might be a good candidate for a pre-deploy QA PR, so that we don't get a confusingly named job stuck in the SQLAlchemy store.
> NS-168 Generate required schemas on startup if necessary

- .ebextensions/41_install_pandas.config
- .travis.yml
- README.md
- requirements.txt
https://jira.ets.berkeley.edu/jira/browse/NS-178
`pandas` upgrade seems like a good idea. Read v0.23.2 notes: https://github.com/pandas-dev/pandas/releases
> NS-178, minor upgrades: SQLAlchemy, pandas, pytest, etc.

- nessie/merged/student_terms.py
https://jira.ets.berkeley.edu/jira/browse/NS-187
Where "on hand" means "available from a fast SQL query rather than a slow API loop."
The client can decide whether to show it or not. BOAC appears to be up to the responsibility.
> NS-187 Nessie should provide any midterms/drops data it has on hand

- nessie/sql_templates/create_boac_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-205
While we prefer GROUP BY to DISTINCT in Redshift Spectrum queries, it's not possible here because of dynamic columns set by CASE statements. Fortunately, a test run suggests we aren't taking a huge performance hit.
> NS-205 Guard against duplication in Canvas Data sources

- config/testext.py
- nessie/lib/mockingbird.py
- requirements.txt
- tests/test_externals/test_s3.py
- tests/test_externals/test_sis_enrollments_api.py
- tests/test_jobs/test_resync_canvas_snapshots.py
- tests/test_jobs/test_sync_canvas_snapshots.py
- tests/test_jobs/test_sync_file_to_s3.py
- tests/util.py
https://jira.ets.berkeley.edu/jira/browse/NS-224
(For background on the responses package, see https://cra.mr/2014/05/20/mocking-requests-with-responses - it's designed after httpretty but simpler, which fits our usage and seems to cause fewer conflicts.)
> NS-224 Brain transplant for Mockingbird: httpretty -> responses

- nessie/lib/analytics.py
- tests/test_lib/test_analytics.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1259
Follow-up to #209. For matrix plotting we need comparative percentiles, not just raw values.
> BOAC-1259 Include comparative percentiles for course means

- nessie/jobs/import_degree_progress.py
- nessie/jobs/import_sis_enrollments_api.py
- nessie/jobs/import_sis_student_api.py
- nessie/lib/util.py
- tests/test_jobs/test_import_degree_progress.py
- tests/test_jobs/test_import_sis_enrollments_api.py
- tests/test_jobs/test_import_sis_student_api.py
The briefer commit is the one that addresses https://jira.ets.berkeley.edu/jira/browse/NS-226. Added test coverage is just an olive on top.
>  NS-226 Move current-date calls out of function signatures; test coverage

- nessie/sql_templates/create_lrs_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-240
Per review from @sandeepmjay on #220.
`varchar(max)` is used elsewhere in Nessie and presently works out to 65535.
https://docs.aws.amazon.com/redshift/latest/dg/r_Character_types.html#r_Character_types-storage-and-ranges
> NS-240 Support max varchar length on LRS statements in Redshift

- config/default.py
- nessie/factory.py
- tests/test_factory.py
https://jira.ets.berkeley.edu/jira/browse/NS-235
This should let us enable background-thread pools on Nessie-worker instances while letting Nessie-master proceed By All Threads Necessary.
> NS-235 WORKER_QUEUE_ENABLED should only affect Worker instances

- config/default.py
- nessie/api/job_controller.py
- nessie/externals/glue.py
- nessie/jobs/create_lrs_glue_jobs.py
- nessie/jobs/transform_lrs_incrementals.py
- nessie/sql_templates/glue_templates/caliper_input_schema.json
- nessie/sql_templates/glue_templates/caliper_transforms.py
Commit contains the following:
1.	Glue external based on boto3 for nessie
2.	Nessie create lrs glue job
3.	API routes for triggering create lrs glue job
4.	Glue templates containing the pyspark scripts to run to explode canvas caliper incremental into flat files
5.	Glue template having curated canvas caliper schema to recognize the shape of various caliper events to resolve spark dataframe before spark explode operations.
6.	Configuration file updates required to run Glue jobs.
> [NS-244] Glue externals to nessie and Create LRS glue background job, pyspark caliper etl scripts and caliper schema templates.

- requirements.txt
https://jira.ets.berkeley.edu/jira/browse/NS-268
Ceremonial upgrades following `qa` branch cut.
* https://www.sqlalchemy.org/blog/2018/09/19/sqlalchemy-1.2.12-released
* https://ldap3.readthedocs.io/changelog.html
> NS-268, minor upgrades in Nessie py deps

- buildspec.yml
https://jira.ets.berkeley.edu/jira/browse/NS-249
CodePipeline no happy:
```
Phase complete: BUILD Success: false
Phase context status code: COMMAND_EXECUTION_ERROR Message: 
Error while executing command: npm run build-vue. Reason: exit status 1
```
> NS-249, buildspec, for CodePipeline, needs @vue/cli in order to run build

- buildspec.yml
https://jira.ets.berkeley.edu/jira/browse/NS-249
One last `sudo` tweak. CodePipeline succeeded pulling from this branch. Vue.js homepage is now loading at https://app-master-dev.ets-berkeley-nessie.net/
> NS-249, sudo is required on npm install

- nessie/jobs/import_lrs_incrementals.py
- nessie/jobs/migrate_lrs_incrementals.py
https://jira.ets.berkeley.edu/jira/browse/NS-274
Variable names, slash handling in paths, remove redundant unload step.
> NS-274 Small but crucial Caliper pipeline fixes

- nessie/lib/analytics.py
- requirements.txt
https://jira.ets.berkeley.edu/jira/browse/BOAC-1272
This is functionally Paul Kerschen's https://github.com/paulkerschen/nessie/commit/458f2bfe5133a31e51eed83c5715d53933b50213
My only changes were to keep the old percentile property alongside the new one, and to add a display percentile to the course mean.
I'll wait to submit the corresponding BOAC PR until after this gets a chance to run.
> BOAC-1272 Calculate against unique scores for optimal matrix spread

- nessie/lib/analytics.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1272
Correction to https://github.com/ets-berkeley-edu/nessie/pull/263 , which sometimes claimed that the Mean Man was in the "30th" percentile, etc.
> BOAC-1272 Change incorrect Mean Man display percentile

- src/components/Jobs.vue
- src/main.ts
https://jira.ets.berkeley.edu/jira/browse/NS-299
`npm run build-vue` has stricter standards compared to `npm run serve` (used for local dev). The inline "eslint:warn" will be addressed later.
> NS-299, 'npm run build-vue' failed due to improper vue-lodash import

- nessie/jobs/create_canvas_schema.py
- nessie/lib/util.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1431
It's always midnight somewhere.
QA-first PR because the qa tier is where it needs to be tried out. This pattern already exists in nessie/jobs/create_sis_schema.py, and probably should have been ported over here before now.
> [QA] BOAC-1431 Allow fallback to yesterday's Canvas data in external schema

- .eslintrc.js
- src/router.ts
- src/store.ts
Following up on a discussion with @johncrossman & @lyttam (which would've also included @paulkerschen if he'd been available)...
Nessie/BOA's wee bit of TypeScript code includes some explicit function-parameter typing of "any" even though the code clearly does expect an object with a predictable structure.
None of us are eager to relive the full-on interface/class Java experience. But the newer JS frameworks push TS hard, and if we're going to use it, it would be nice to trim the noise. So we'll try this:
* Fill in more real-types when it's easy (e.g., this PR).
* Instead of explicitly defaulting all arguments to "any", we will leave them explicitly _untyped_, which in turn means continuing to disable "noImplicitAny" checks. That way it'll be easy to see which typing has been thought out …
> NOJIRA Replace some TypeScript punts; fix linting

- nessie/jobs/background_job.py
I don't know if this is the whole problem behind https://jira.ets.berkeley.edu/jira/browse/NS-311, but it's a problem. This bug has been waiting to bite us ever since we split off worker-style async runs (using a queue) from master-style (no queue).
> NS-311 Neither master nor worker envs should start background jobs from tests

- nessie/api/job_controller.py
- nessie/jobs/generate_merged_student_feeds.py
- nessie/jobs/scheduling.py
- tests/test_api/test_schedule_controller.py
https://jira.ets.berkeley.edu/jira/browse/NS-331
Required flipping GenerateMergedStudentFeeds defaults to match the nightly job.
Since these scheduling conflicts have been hitting production for a while, if this change tests out I think it should probably go into the QA branch as well.
> NS-331 Avoid scheduling conflicts between the final two BOA jobs

- nessie/jobs/generate_canvas_caliper_analytics.py
News flash, kid: in the real world your timestamps don't always arrive in perfect order.
https://jira.ets.berkeley.edu/jira/browse/NS-309
> NS-309 Caliper transformation: adjust tolerance for timestamp sanity check

- nessie/externals/redshift.py
- nessie/jobs/refresh_canvas_data_catalog.py
The PR contains the following logic,
1) get an inventory of all S3 objects in a prefix for canvas-data.
2) Isolate unique table names from the s3 objects  extracted from the daily location
3) Run data verification processes to identify bad migration scenarios 
The logic ensures that all the canvas-data files sync are cataloged and verified. Tables for which schema exist but there is no data are omitted in the process.
https://jira.ets.berkeley.edu/jira/browse/NS-379
> NS-379 Improve the verification scheme for the generated data catalog

- nessie/sql_templates/index_sis_advising_notes.template.sql
Handling UCBCONVERSION notes properly in search results requires this column in the index table.
https://jira.ets.berkeley.edu/jira/browse/BOAC-1882
> BOAC-1882 BOAC-1884 Add created_by to advising notes search index

- nessie/jobs/generate_merged_enrollment_term.py
https://jira.ets.berkeley.edu/jira/browse/NS-460
#385 was missing a rather important line.
> NS-460 Don't unmerge assignment submissions after we worked so hard to merge them

- nessie/sql_templates/create_asc_advising_notes_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2110
Like SIS notes, ASC notes can have one ID for many student SIDs - however the SID-ID combination should be unique.
> BOAC-2110: Adds unique key to ASC notes schema

- config/default.py
- nessie/lib/util.py
- nessie/sql_templates/create_sis_advising_notes_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-540
The historical snapshot of SIS notes data has been copied to s3://la-nessie-protected-dev/sis-data/historical/advising-notes.  This PR updates the code to point to the new location.  
I also updated the nessie-dev deploy config accordingly.  Once deployed and tested, I'll remove the old S3 folders that will no longer be in use.
> NS-540: Points to new S3 location for historical SIS notes

- buildspec.yml
https://jira.ets.berkeley.edu/jira/browse/NS-543
> NS-528, buildspec.yml to v0.2 spec, uses 'runtime versions'

- nessie/jobs/create_asc_advising_notes_schema.py
- nessie/sql_templates/create_asc_advising_notes_schema.template.sql
- nessie/sql_templates/index_asc_advising_notes.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2238
I thought it made sense to add these tables to the existing `boac_advising_asc` schema, but I could alternatively add them to the `boac_advising_notes` schema or create a new schema for them.
> BOAC-2238: Adds advising note search index to ASC schema

- nessie/sql_templates/index_asc_advising_notes.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-580
When a note is edited after it is created, ASC will send us two records - we want only the most recent one.
> NS-580: Discards previous versions of an ASC note

- nessie/sql_templates/index_asc_advising_notes.template.sql
- nessie/sql_templates/index_sis_advising_notes.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2435
Without this info, locally run BOAC code displayed search results with a timezone shift, neatly obscuring a separate BOAC-side bug (https://github.com/ets-berkeley-edu/boac/pull/1688).
> BOAC-2435 Add timezone info to RDS advising note indexes

- tox.ini
See also:  https://github.com/ets-berkeley-edu/boac/commit/be837490fdc6b79c3381a84e95f2726c35d9b7ea
> Lock down pydocstyle version for linting

- nessie/jobs/scheduling.py
https://jira.ets.berkeley.edu/jira/browse/NS-575
After Junction j104 is released, SIS notes data will be uploaded to S3 at 8pm each day.  I think it makes sense to group all the Nessie notes jobs together, so the SIS notes schema will be created right after the ASC notes schema at 3:15am.
> NS-575: Adds SIS note import to schedule

- requirements.txt
https://jira.ets.berkeley.edu/jira/browse/BOAC-2478
See `psycopg2` error in https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logEventViewer:group=/aws/elasticbeanstalk/nessie-master-dev/var/log/eb-activity.log;stream=i-0933c40f9b543b7b3;start=2019-07-14T18:53:18Z
> BOAC-2478, revert psycopg2 to v2.7.7

- nessie/externals/sis_student_api.py
https://jira.ets.berkeley.edu/jira/browse/NS-612
The current production release of the V2 Students API returns info on discontinued academic plans when `inc-completed-programs` are requested. But the upcoming release (currently in QA) will require a `inc-inactive-programs=true` parameter as well.
> NS-612 Handle upcoming change to SIS V2 Students API parameter

- config/default.py
- fixtures/sis_student_api_v1_11667051.json
- fixtures/sis_student_api_v1_1234567890.json
- fixtures/sis_student_api_v1_2345678901.json
- fixtures/students.sql
- nessie/externals/sis_student_api.py
- nessie/jobs/generate_merged_student_feeds.py
- nessie/jobs/import_sis_student_api.py
- nessie/lib/queries.py
- nessie/merged/sis_profile_v1.py
- nessie/sql_templates/create_student_schema.template.sql
- tests/conftest.py
- tests/test_externals/test_sis_student_api.py
- tests/test_jobs/test_import_sis_student_api.py
- tests/test_merged/test_sis_profile.py
- tests/test_merged/test_sis_profile_v1.py
https://jira.ets.berkeley.edu/jira/browse/NS-637
Because the V2 API integration tried to keep upper-layer data feeds stable, the V1 reversion can (theoretically) be swapped back in without much disruption. As usual with this massive operation, though, the only way to test that assumption is to try it on a running system and live with any delays that result.
In other words, a close code review would be even more appreciated than usual.
> NS-637 Fall back to V1 SIS Students API

- nessie/sql_templates/create_sis_advising_notes_historical_schema.template.sql
- nessie/sql_templates/index_advising_note_authors.template.sql
- nessie/sql_templates/index_sis_advising_notes.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2393
These commands need to be run once, so it makes more sense to do them as a release step.
> BOAC-2393: Moves DROP TABLE commands to release instructions

- nessie/jobs/create_sis_advising_notes_schema.py
- nessie/jobs/index_advising_note_authors.py
- nessie/sql_templates/create_advising_note_authors.template.sql
- nessie/sql_templates/index_sis_advising_notes.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2395
This moves the advising_note_authors table from the SIS-specific schema to the general advising notes schema and adds advisors from ASC and E&I.  This will make it easier to return ASC and E&I notes in a search by author in BOA.
> BOAC-2395: Expands advising_note_authors to include ASC and E&I

- requirements.txt
https://jira.ets.berkeley.edu/jira/browse/NS-697
And `Flask-SQLAlchemy` to 2.4, as in BOA.
> NS-697, upgrade to Flask 1.1 (Nessie)

- nessie/lib/util.py
- nessie/merged/sis_profile.py
- nessie/merged/sis_profile_v1.py
- tests/test_merged/test_sis_profile.py
- tests/test_merged/test_sis_profile_v1.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2753
I changed keys `unitsMaxOverride` and `unitsMinOverride` to  `unitsMax` and `unitsMin` because they are not necessarily "overrides" – the attributes might carry default values. If this PR is merged then I'll submit (1) a QA PR and (2) the necessary BOA PRs.
> BOAC-2753, until SISRP-48560 is resolved, we treat 0.5 as 12, the expected min-units per term

- nessie/jobs/migrate_sis_advising_note_attachments.py
- nessie/jobs/verify_sis_advising_note_attachments.py
- nessie/lib/util.py
- tests/conftest.py
- tests/test_jobs/test_migrate_sis_advising_note_attachments.py
- tests/test_jobs/test_verify_sis_advising_note_attachments.py
- tests/test_lib/test_util.py
https://jira.ets.berkeley.edu/jira/browse/NS-696
The Migrate and Verify jobs now share the code that constructs a range of dates from the last successful run of the Migrate job to today.
The dates are converted from UTC to PST to match the dated folder structure created by Darlene's script, which runs in PST.
> NS-696: Standardizes time zones across SIS attachment jobs

- nessie/jobs/verify_sis_advising_note_attachments.py
- tests/test_jobs/test_verify_sis_advising_note_attachments.py
- tests/test_lib/test_util.py
https://jira.ets.berkeley.edu/jira/browse/NS-696
Whereas the "since last successful run" logic has proved problematic for the VerifySisAdvisingNoteAttachments job, and whereas the work it does is inexpensive (relative to the Migrate job's work of copying files), the job will now validate all SIS attachments in S3 by default. 
We can still narrow it down to a specific year, month, or date by running it manually with a datestamp param.
> NS-696: Further simplifies the verify attachments job

- nessie/externals/sis_student_api.py
The latest turn of the screw from https://jira.ets.berkeley.edu/jira/browse/NS-682
This is kind of hokey but I couldn't come up with anything better. If we decide to leave the extra protection in place, we should refactor a bit so as to return the parsed JSON up the call stack instead of paying the decoding price twice.
> NS-682 Log & move past faulty JSON payloads from SIS API

- requirements.txt
https://jira.ets.berkeley.edu/jira/browse/NS-751
I'm not convinced this will work. See Jira for log snippet from failed CodePipeline deploy.
> NS-751, require 'setuptools>=30.0.0' per CodePipeline complaint

- .ebextensions/00_ami.config
https://jira.ets.berkeley.edu/jira/browse/NS-755
This intervention is needed because an AWS bug is causing this setting to override the console-side config.
> NS-755: Increases instance size to m5.large

- nessie/lib/berkeley.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3496
Note that this addition doesn't actually change code behavior, but why not be explicit.
> BOAC-3496 Add DPN grading basis

- nessie/sql_templates/create_advising_note_authors.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-877
An existing note author's CalNet data changed yesterday such that they no longer have an SID.
> NS-877: Removes NOT NULL constraint from note author SID

- requirements.txt
https://jira.ets.berkeley.edu/jira/browse/NS-912
Nessie-dev jobs failed with "automatic start_tls befored bind not successful". Possibly due to recent ldap upgrade (PR #747). See "version 2.8 of ldap3 introduced SafeSync" at https://ldap3.readthedocs.io/en/latest/
> NS-912, revert ldap3 to v2.7 (was v2.8)

- nessie/api/job_controller.py
- nessie/jobs/import_piazza_api_data.py
- nessie/jobs/transform_piazza_api_data.py
- nessie/lib/util.py
As previously written, the Import job required that something be included in the URL to indicate to the job which archive to fetch (e.g. "daily-2020-09-12", or just "daily", for the latest daily zip). However, when running as a scheduled job this path element is not being provided and so it fails.
Same applies to the Transform job.
I have simplified the routes and made that path element optional, in which case it defaults to "latest", i.e. "daily-MMMM-YY-DD", for date of run.
> NS-974, refactor routes in nessie piazza jobs

- nessie/api/job_controller.py
- nessie/jobs/import_piazza_api_data.py
- nessie/jobs/transform_piazza_api_data.py
- nessie/lib/util.py
Correcting a couple "overdesign" and "overimplementation" issues:
1. Nessie itself makes job start and job end entries is the job queue. No need to do that twice! Doing so make two entries appear for each job.
2. Also realized that the previous implementation was not returning job queue 'details' properly, and so they were not appearing.
3. Refactored a bit to allow Nessie to take care of some error conditions, rather than try to do it myself with try: ... except: blocks. This simplified a bunch of things!
4. The optional "archive" value was not being parsed correctly. This wasn't causing a problem per se, but it should match the archive naming convention in use by Piazza.
> NS-974, job queue entries only appear once now, correct filename parsing

- nessie/jobs/import_canvas_enrollments_api.py
- nessie/jobs/import_degree_progress.py
- tests/test_jobs/test_import_degree_progress.py
https://jira.ets.berkeley.edu/jira/browse/NS-1029
Sadly, I had to disable unit test because the new SQL syntax is incompatible with Postgres (mock Redshift when pytest).
> NS-1029, ImportDegreeProgress: Use temp external schema rather than a COPY command

- nessie/api/status_controller.py
- src/main.ts
- src/mixins/Context.vue
- src/router.ts
- src/store/modules/context.ts
- src/views/Status.vue
- tests/test_api/test_status_controller.py
https://jira.ets.berkeley.edu/jira/browse/NS-1076
One more front-end tweak: I borrowed a snippet of Diablo code to simplify config-related mixin. Plus, a more informative and cleaner `/status` page.
> NS-1076, less config-related mixin code for Nessie front-end

- nessie/lib/util.py
- nessie/sql_templates/create_edl_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1052
This will limit `student_profile_index` rows to students that have a UID.
> NS-1052: Adds UID to profile index, sourced from staging table

- nessie/jobs/import_degree_progress.py
- nessie/jobs/import_registrations.py
- nessie/jobs/import_registrations_hist_enr.py
- nessie/lib/util.py
- nessie/sql_templates/create_edl_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1081
Not all calls to `get_s3_sis_api_daily_path()` should use EDL bucket. Opt-in is safer.
> NS-1081, get_s3_sis_api_daily_path has opt-in to use 'edl' S3 bucket

- nessie/jobs/create_edl_schema.py
- nessie/sql_templates/create_edl_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1080
And, I think it was the semi-colon in the inline comment that caused a problem. I tested this SQL file on nessie-dev (hacked it with `vi`) and it works.
> NS-1080, fix column names on student_enrollment_data query

- nessie/externals/b_connected.py
- nessie/jobs/background_job.py
https://jira.ets.berkeley.edu/jira/browse/NS-1091
I also removed redundant `EMAIL_FEATURE_ENABLED` check. The diff is far simpler than it looks: review with `?w=1`.
> NS-1091, put more failed-job info in alert_email

- nessie/api/analyze_edl_controller.py
- nessie/routes.py
https://jira.ets.berkeley.edu/jira/browse/NS-1104
This controller can be used for various EDL comparisons.
> NS-1104, API endpoint: /api/analyze_edl/import_registrations/<sid> (nessie-local only)

- .ebextensions/00_ami.config
This is a temporary change that may be reversed in May when the feature is turned on globally. Jira is NS-1143.
> Adding new 00_ami.config for NS-1143

- .ebextensions/00_ami.config
Reversing EnhancedHealthAuthEnabled which had been added for testing purposes.
> NS-1157 Removing EnhancedHealthAuthEnabled because default value is set to true

- nessie/sql_templates/create_advisor_schema.template.sql
- nessie/sql_templates/index_advisors.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1176
One more follow-up to #908. Traced back to the source, that column turns out to refer to student ids, not advisor ids.
> NS-1176 Remove misleading uid column from advisor/dept table

- nessie/api/errors.py
- tox.ini
https://jira.ets.berkeley.edu/jira/browse/NS-1189
> NS-1189, upgrade to flake8 3.9.2 and fix lint-py errors

- nessie/lib/queries.py
https://jira.ets.berkeley.edu/jira/browse/NS-1209
EDL replacement for `undergrads_schema.students` was the main challenge. The other datasources in play (ASC, COE, and the BOA-sourced `non_current_students`) are still used when EDL feature-flag is true.
> NS-1209, get_all_student_ids() from EDL if feature-flag

- nessie/jobs/verify_sis_advising_note_attachments.py
https://jira.ets.berkeley.edu/jira/browse/NS-1231
> NS-1231: Skips attachment file name workaround when using EDL data

- src/views/Status.vue
https://jira.ets.berkeley.edu/jira/browse/NS-1294
> NS-1294, status tab doesn't need version.build cuz it's in header

- nessie/jobs/create_terms_schema.py
- nessie/sql_templates/create_terms_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1243
See Jira for latest stack-trace. Previous version of the postgres function `deduce_term_name()` caused error in Postico console due to f-strings.
> NS-1243, postgres/python proc lang does not like f-strings

- nessie/jobs/create_advisor_schema.py
- nessie/sql_templates/create_advisor_note_permissions.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1306
If EDL then we have a scaled down `redshift_schema_advisor`.
> NS-1306, after EDL cutover, we will continue to rely on BOA_ADV_NOTES_ACCESS_VW (EDO db)

- nessie/sql_templates/create_edl_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1339
The Junction query is limited to SIDs in s3:calnet-data/sids/snapshot000 so our EDL query must replicate via SQL JOIN.
> NS-1339, ext query to populate edl.academic_standing join on calnet.advisees

- nessie/lib/queries.py
https://jira.ets.berkeley.edu/jira/browse/NS-1354
We pick up the expected `matriculation_term_cd`, matching v2 API results.
> NS-1354, EDL academic_plan_data query tweak to match v2 student API

- nessie/lib/queries.py
https://jira.ets.berkeley.edu/jira/browse/NS-1354
See latest comment/screenshot in Jira above. This query tweak is in line with what we have been extracting from v2 student API.
> NS-1354, PRGC is acceptable statusInPlan.code when querying edl_plans
