ets-berkeley-edu/nessie

- .travis.yml
- nessie/api/job_controller.py
- nessie/externals/s3.py
- requirements.txt
- tests/conftest.py
- tests/test_api/test_job_controller.py
- tests/test_externals/test_s3.py
- tests/test_jobs/test_sync_file_to_s3.py
https://jira.ets.berkeley.edu/jira/browse/LA-304
> LA-304 S3 client code, including streaming multipart uploads

- nessie/externals/s3.py
- nessie/jobs/sync_canvas_dumps.py
- nessie/jobs/sync_file_to_s3.py
- tests/test_externals/test_s3.py
- tests/test_jobs/test_sync_canvas_dumps.py
https://jira.ets.berkeley.edu/jira/browse/LA-340
> LA-340 S3 cleanup routine for obsolete files

- nessie/externals/redshift.py
- nessie/jobs/background_job.py
- nessie/jobs/create_canvas_schema.py
- nessie/jobs/sync_canvas_snapshots.py
- nessie/sql_templates/create_db.template.sql
- nessie/sql_templates/materialized_views.template.sql
- nessie/sql_templates/repoint_db.template.sql
https://jira.ets.berkeley.edu/jira/browse/LA-321
No tests yet, but there are enough oddities here to call for an early review.
> LA-321 Add creation of Canvas data schema in Redshift

- nessie/sql_templates/create_boac_schema.template.sql
- nessie/sql_templates/create_canvas_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/LA-368
> LA-368 Bring BOAC and Canvas schema templates up to date with Data Loch

- config/default.py
- nessie/jobs/background_job.py
- nessie/lib/util.py
- requirements.txt
The easiest bit of https://jira.ets.berkeley.edu/jira/browse/LA-323
> LA-323 Determine the current date string based on LA timezone

- .ebextensions/00_ami.config
- .ebextensions/10_install_httpd.config
- .ebextensions/20_download_local_configuration.config
- .ebextensions/30_create_cloudwatch_conf.config
- .ebextensions/99_delayed_script.config
https://jira.ets.berkeley.edu/jira/browse/LA-380
I'd like to get a jump on peer review. The TODO item: `.ebextensions/10_install_httpd.config` > nessie_openssl_x509.crt
> LA-380, Nessie .ebextensions (SSL cert coming soon)

- nessie/sql_templates/create_boac_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-676 - see most recent comments
I hope we're now within sight of Point Diminishing Returns....
> BOAC-676 Deal with zero-max-score Complete/Incomplete assignments

- nessie/sql_templates/create_boac_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/LA-400
> LA-400 Improve performance of assignment timeliness query

- nessie/api/status_controller.py
https://jira.ets.berkeley.edu/jira/browse/LA-402
> LA-402, route '/' will go to '/api/ping'

- .ebextensions/00_ami.config
- .gitignore
- buildspec.yml
https://jira.ets.berkeley.edu/jira/browse/LA-407
> LA-407, new SG settings for custom VPC

- config/default.py
- nessie/externals/s3.py
- nessie/jobs/background_job.py
- nessie/jobs/create_sis_schema.py
- nessie/sql_templates/create_sis_schema.template.sql
- tests/test_jobs/test_create_sis_schema.py
https://jira.ets.berkeley.edu/jira/browse/LA-408
> LA-408 Merge daily and historical SIS data snapshots via manifest file

- config/testext.py
- tests/conftest.py
- tests/test_externals/test_s3.py
- tests/test_jobs/test_sync_canvas_snapshots.py
- tests/test_jobs/test_sync_file_to_s3.py
https://jira.ets.berkeley.edu/jira/browse/LA-411
> LA-411 Update testext suite to use a shared S3 bucket

- .ebextensions/20_download_local_configuration.config
https://jira.ets.berkeley.edu/jira/browse/LA-413
> LA-413 Suppress PYTHONPATH for AWS CLI command in .ebextensions

- nessie/externals/s3.py
https://jira.ets.berkeley.edu/jira/browse/LA-416
> LA-416 Don't log S3 404s as errors

- config/default.py
- nessie/jobs/background_job.py
- nessie/jobs/queue.py
https://jira.ets.berkeley.edu/jira/browse/LA-419
This seems to work locally; let's try it in The Cloud.
> LA-419 Support queued background job processing

- config/default.py
- nessie/api/job_controller.py
- nessie/externals/redshift.py
- nessie/jobs/background_job.py
- nessie/jobs/create_canvas_schema.py
- nessie/jobs/create_sis_schema.py
- nessie/jobs/generate_boac_analytics.py
- nessie/jobs/generate_intermediate_tables.py
- nessie/jobs/scheduling.py
https://jira.ets.berkeley.edu/jira/browse/LA-412
> LA-412 Add support for chained background jobs

- nessie/__init__.py
> NOJIRA Nessie starts out at version 2.0

- nessie/externals/redshift.py
- nessie/sql_templates/create_boac_schema.template.sql
- nessie/sql_templates/create_intermediate_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/LA-448
I ran this locally; results are in `dev_johncrossman_boac` (data_loch_dev).
> LA-448, rename 'user_course_scores' view and add last_activity_at column

- nessie/sql_templates/create_boac_schema.template.sql
- nessie/sql_templates/create_intermediate_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-880
The commit messages should tell the story.
> BOAC-880 Revisions to Nessie's derived schemas

- config/default.py
- nessie/api/job_controller.py
- nessie/jobs/resync_canvas_snapshots.py
- nessie/jobs/scheduling.py
- nessie/jobs/sync_canvas_snapshots.py
- nessie/lib/metadata.py
- tests/test_api/test_job_controller.py
- tests/test_jobs/test_resync_canvas_snapshots.py
- tests/test_jobs/test_sync_canvas_snapshots.py
https://jira.ets.berkeley.edu/jira/browse/LA-332
https://jira.ets.berkeley.edu/jira/browse/LA-426
> LA-332 LA-426 Resync job for Canvas snapshots

- nessie/sql_templates/create_intermediate_schema.template.sql
- nessie/sql_templates/create_sis_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-46
Next down in the waterfall is BOAC itself.
> NS-46 Include SIS course title in Nessie

- nessie/jobs/background_job.py
- nessie/jobs/create_sis_schema.py
- tests/test_jobs/test_create_sis_schema.py
https://jira.ets.berkeley.edu/jira/browse/NS-75
> NS-75 Nessie should accept SIS S3 data created before midnight

- nessie/sql_templates/create_canvas_schema.template.sql
- nessie/sql_templates/create_intermediate_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-885
Surprisingly, this seems to be the first time anyone's wanted it.
> BOAC-885 Expose a few more Canvas Course properties for BOAC

- nessie/sql_templates/create_intermediate_schema.template.sql
- nessie/sql_templates/create_sis_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-76
https://jira.ets.berkeley.edu/jira/browse/NS-46
> NS-76 NS-46 Fix Redshift's CSV parsing; add more SIS section data

- nessie/sql_templates/create_sis_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-908
> BOAC-908 Parse SIS courses.is_primary as Boolean rather than string

- nessie/__init__.py
Slowly we turn, step by step, inch by inch...
> NOJIRA, bump Nessie version to 2.1

- nessie/sql_templates/create_boac_schema.template.sql
QA version of https://github.com/ets-berkeley-edu/nessie/pull/54
Fix tested OK on Nessie-Dev.
> [QA] BOAC-917 A student without scores might lack a course_score_fact row

- nessie/sql_templates/create_boac_schema.template.sql
Removed duplicates from the final view by ignoring canvas_enrollment_ids and adding a distinct query while tracking assignment submissions. 
https://jira.ets.berkeley.edu/jira/browse/NS-90
> [NS-90] Remove duplicates on assignment_submissions_scores materialized view

- nessie/sql_templates/create_boac_schema.template.sql
QA version of https://github.com/ets-berkeley-edu/nessie/pull/56
> [QA] NS-90 Removed duplicates from the final view

- nessie/__init__.py
- requirements.txt
https://jira.ets.berkeley.edu/jira/browse/NS-101
> NS-101, nessie/__init__.py gets the SQLAlchemy basics

- config/default.py
- fixtures/sis_student_api_11667051.json
- fixtures/sis_student_api_2345678901.json
- nessie/externals/sis_student_api.py
- tests/test_externals/test_sis_student_api.py
https://jira.ets.berkeley.edu/jira/browse/NS-85
Swiped from BOAC all round.
> NS-85 Client and tests for SIS student API

- config/default.py
- fixtures/sis_enrollments_api_11667051_2162.json
- fixtures/sis_enrollments_api_11667051_2172.json
- fixtures/sis_enrollments_api_11667051_2178.json
- nessie/externals/sis_enrollments_api.py
- tests/test_externals/test_sis_enrollments_api.py
https://jira.ets.berkeley.edu/jira/browse/NS-87
You see where this is going...
> NS-87 Client, tests and fixtures for SIS enrollments API

- config/default.py
- fixtures/sis_degree_progress_11667051.xml
- fixtures/sis_degree_progress_9999999.xml
- nessie/externals/sis_degree_progress_api.py
- requirements.txt
- tests/test_externals/test_sis_degree_progress_api.py
https://jira.ets.berkeley.edu/jira/browse/NS-86
Once again, `@stow` temporarily disabled.
> NS-86 Client, tests and fixtures for SIS degree progress API

- .travis.yml
- README.md
- config/default.py
- nessie/factory.py
- nessie/models/development_db.py
- scripts/db/drop_schema.sql
- scripts/db/schema.sql
- tests/conftest.py
https://jira.ets.berkeley.edu/jira/browse/NS-103
More, more, more.
> NS-103, nessie_test db init during tests; schema.sql and drops

- nessie/models/base.py
https://jira.ets.berkeley.edu/jira/browse/NS-103
> NS-103, Base db.Model class

- nessie/externals/sis_degree_progress_api.py
- nessie/externals/sis_student_api.py
- nessie/lib/berkeley.py
- nessie/models/development_db.py
- nessie/models/json_cache.py
- requirements.txt
- scripts/db/drop_schema.sql
- scripts/db/schema.sql
https://jira.ets.berkeley.edu/jira/browse/NS-104
We may not need as much staging-table fanciness on a machine that isn't trying to serve BOAC at the same time, but there doesn't seem to be any harm in keeping it around for now.
> NS-104 Add JsonCache

- nessie/externals/asc_athletes_api.py
- nessie/jobs/import_asc_athletes.py
- tests/test_externals/test_asc_athletes_api.py
https://jira.ets.berkeley.edu/jira/browse/NS-97
> NS-97, bring back JsonCache in ASC API integration

- nessie/jobs/import_degree_progress.py
- tests/test_jobs/test_import_degree_progress.py
https://jira.ets.berkeley.edu/jira/browse/NS-86
> NS-86 Background job for SIS degree progress import

- requirements.txt
https://jira.ets.berkeley.edu/jira/browse/NS-110
"Release 1.2.8 includes a fairly broad spectrum of fixes, including fixes for some memory/synchronization issues within the connection pool, automap and statement caching functionalities..."
https://www.sqlalchemy.org/blog/#sqlalchemy-1.2.8-released
> NS-110, upgrade SQLAlchemy

- README.md
- run.py
https://jira.ets.berkeley.edu/jira/browse/NS-102
> NS-102, use 'flask initdb' to create RDS schema

- nessie/jobs/import_sis_student_api.py
- tests/test_jobs/test_import_sis_student_api.py
https://jira.ets.berkeley.edu/jira/browse/NS-85
> NS-85 SIS student API background job

- config/default.py
- nessie/externals/sis_enrollments_api.py
- nessie/jobs/import_sis_enrollments_api.py
- tests/test_jobs/test_import_sis_enrollments_api.py
https://jira.ets.berkeley.edu/jira/browse/NS-87
> NS-87 SIS enrollments API background job

- nessie/sql_templates/create_boac_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-884
Another waltz round the floor...
> BOAC-884 Most graded assignments should not be treated as "missing"

- run.py
- scripts/migrate/NS-102_create_nessie_db_on_rds.sh
https://jira.ets.berkeley.edu/jira/browse/NS-102
I did necessary `chmod` on the script. Verified in dev.
> NS-102, shell script does nasty business of running 'flask initdb'

- nessie/externals/redshift.py
- nessie/jobs/create_canvas_schema.py
- nessie/jobs/create_sis_schema.py
- nessie/sql_templates/create_canvas_schema.template.sql
- nessie/sql_templates/create_sis_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-94
Tested against working schemas on dev server.
> NS-94 Safer implementation of DROP EXTERNAL SCHEMA

- README.md
- nessie/api/job_controller.py
- nessie/jobs/background_job.py
- nessie/jobs/scheduling.py
- nessie/models/util.py
- tests/test_api/test_job_controller.py
https://jira.ets.berkeley.edu/jira/browse/NS-89
> NS-89 Move scheduler job store to SQLAlchemy; add advisory locks

- nessie/api/status_controller.py
- requirements.txt
- tests/test_api/test_status_controller.py
https://jira.ets.berkeley.edu/jira/browse/NS-116
https://jira.ets.berkeley.edu/jira/browse/NS-117
* release-instructions will get Nagios change request
* minor boto3 upgrade (see NS-117 description)
> NS-116, RDS status added to /api/ping; boto3 upgrade

- nessie/api/schedule_controller.py
- nessie/jobs/scheduling.py
- tests/test_api/test_schedule_controller.py
https://jira.ets.berkeley.edu/jira/browse/NS-89
Here's an important little follow-up to #84... we don't want to lose our modifications every time the app deploys or restarts.
> NS-89 Preserve modified schedules on app restart

- scripts/deploy_nessie_config.sh
https://jira.ets.berkeley.edu/jira/browse/NS-120
As seen in BOAC.
> NS-120, deploy Nessie configs from S3 to local EC2 instance

- nessie/jobs/import_asc_athletes.py
- nessie/sql_templates/create_asc_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-121
docs on `org.openx.data.jsonserde.JsonSerDe`: https://docs.aws.amazon.com/athena/latest/ug/json.html
> NS-121, populate ASC Redshift schema with athletics, students, student_athletes

- nessie/externals/s3.py
- nessie/jobs/create_sis_schema.py
- nessie/models/json_cache.py
- tox.ini
https://jira.ets.berkeley.edu/jira/browse/NS-124
Complements BOAC's PR https://github.com/ets-berkeley-edu/boac/pull/689
> NS-124, flake8-builtins to avoid builtin/variable name collision

- config/default.py
- nessie/api/auth_helper.py
- nessie/lib/dispatcher.py
- tests/util.py
https://jira.ets.berkeley.edu/jira/browse/NS-123
We'll want to add two new lines to nessie-dev config before deploying.
> NS-123 Rename WORKER_USERNAME and WORKER_PASSWORD

- nessie/jobs/background_job.py
- nessie/jobs/resync_canvas_snapshots.py
- nessie/jobs/sync_canvas_snapshots.py
- nessie/jobs/sync_file_to_s3.py
- nessie/lib/metadata.py
- nessie/sql_templates/create_metadata_schema.template.sql
- tests/conftest.py
- tests/test_jobs/test_import_asc_athletes.py
- tests/test_jobs/test_import_degree_progress.py
- tests/test_jobs/test_import_sis_enrollments_api.py
- tests/test_jobs/test_import_sis_student_api.py
- tests/test_jobs/test_resync_canvas_snapshots.py
- tests/test_jobs/test_sync_canvas_snapshots.py
- tests/test_jobs/test_sync_file_to_s3.py
- tests/util.py
https://jira.ets.berkeley.edu/jira/browse/NS-92
> NS-92 Log background job status to new metadata table

- nessie/jobs/import_asc_athletes.py
- nessie/lib/asc.py
- nessie/models/development_db.py
- nessie/models/student.py
- nessie/sql_templates/create_asc_schema.template.sql
- nessie/sql_templates/test_db.template.sql
- scripts/db/schema.sql
- tests/test_externals/test_redshift.py
- tox.ini
https://jira.ets.berkeley.edu/jira/browse/NS-125
* UID and name will be pulled from elsewhere.
* Logging `student {index + 1} of {student_count}` is a poor man's progress indicator
> NS-125, drop uid and name from students table (RDS) and improve logging

- nessie/lib/metadata.py
- nessie/sql_templates/create_metadata_schema.template.sql
- run.py
- tests/conftest.py
https://jira.ets.berkeley.edu/jira/browse/NS-126
> NS-126 Add EC2 instance ids to metadata table

- nessie/jobs/background_job.py
- nessie/jobs/resync_canvas_snapshots.py
https://jira.ets.berkeley.edu/jira/browse/NS-92
Important little follow-up to #92.
> NS-92 Follow-up for background job logging

- config/default.py
- nessie/api/job_controller.py
- nessie/jobs/background_job.py
- nessie/jobs/import_asc_athletes.py
- nessie/jobs/import_calnet_data.py
- nessie/sql_templates/create_asc_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-128
* This PR is a sanity check on CalNet data export.
* JsonSerDe fix is in `loch_s3_asc_data_path` value, in background_job.py
> NS-128, CalNet data to S3; JsonSerDe fix in ASC RDS export to S3

- config/default.py
- nessie/api/job_controller.py
- nessie/jobs/background_job.py
- nessie/jobs/create_calnet_schema.py
- nessie/jobs/import_calnet_data.py
- nessie/sql_templates/create_calnet_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-122
* Redshift does not support column type 'array'.
* see `johncrossman_calnet_dev` schema (nessie-dev) if interested in result
> NS-122, CalNet data gets its own schema; 'affiliations' is csv in VARCHAR column

- nessie/sql_templates/create_boac_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-955
> BOAC-955 Fix assignment "late" / "on_time" / "submitted" logic

- nessie/jobs/background_job.py
- nessie/models/util.py
https://jira.ets.berkeley.edu/jira/browse/NS-137
> NS-137 Fully unlock advisory locks; improve logging

- nessie/jobs/generate_merged_student_feeds.py
- nessie/merged/student_terms.py
- nessie/sql_templates/create_student_schema.template.sql
- tests/test_merged/test_student_terms.py
https://jira.ets.berkeley.edu/jira/browse/NS-132
These seem closely enough linked to student profiles to go into the same schema and background job.
> NS-132 Write enrollment term feeds to Redshift

- nessie/jobs/background_job.py
- nessie/models/util.py
https://jira.ets.berkeley.edu/jira/browse/NS-138
> NS-138 Do not leave dangling advisory locks

- nessie/externals/asc_athletes_api.py
- nessie/lib/http.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-982
Nessie version of https://github.com/ets-berkeley-edu/boac/pull/691.
> BOAC-982 Work around ASC API URL transition

- config/default.py
- config/testext.py
https://jira.ets.berkeley.edu/jira/browse/NS-140
This week's theme: the damage one letter can make.
> NS-140 Standardize name of Redshift Student schema

- nessie/models/util.py
https://jira.ets.berkeley.edu/jira/browse/NS-140
Know the worst.
> NS-140 Log and re-raise exceptions during advisory lock

- nessie/jobs/generate_merged_student_feeds.py
- nessie/sql_templates/create_student_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-131
So many searches.
> NS-131 Add uid, name columns to student index table

- config/default.py
- nessie/jobs/background_job.py
- nessie/jobs/generate_merged_student_feeds.py
- nessie/jobs/scheduling.py
- tests/test_api/test_schedule_controller.py
- tox.ini
https://jira.ets.berkeley.edu/jira/browse/NS-143
> NS-143 Make GenerateMergedStudentFeeds term-specific, schedule for current term

- config/default.py
- nessie/jobs/import_asc_athletes.py
- nessie/jobs/import_degree_progress.py
- nessie/jobs/import_sis_enrollments_api.py
- nessie/jobs/import_sis_student_api.py
- nessie/jobs/scheduling.py
- tests/test_api/test_schedule_controller.py
https://jira.ets.berkeley.edu/jira/browse/NS-144
Timing can be tweaked via the scheduler API, but I think this is the order of operations.
> NS-144 More Nessie job scheduling

- fixtures/sis_registrations_api_11667051.json
- nessie/externals/sis_student_api.py
- tests/test_externals/test_sis_student_api.py
https://jira.ets.berkeley.edu/jira/browse/NS-106
Not the top priority, but that's why I did it.
> NS-106 Extract Term GPAs for students

- nessie/jobs/import_degree_progress.py
- nessie/jobs/import_sis_enrollments_api.py
- nessie/jobs/import_sis_student_api.py
- nessie/models/student.py
- tests/test_api/test_schedule_controller.py
https://jira.ets.berkeley.edu/jira/browse/NS-144
> NS-144 Scheduled API import jobs need SID query

- nessie/jobs/background_job.py
- nessie/lib/metadata.py
- nessie/sql_templates/create_metadata_schema.template.sql
- tests/conftest.py
https://jira.ets.berkeley.edu/jira/browse/NS-145
> NS-145 Better logging for unexpected errors in background jobs

- nessie/api/job_controller.py
- nessie/jobs/import_calnet_data.py
- nessie/jobs/import_degree_progress.py
- nessie/jobs/import_sis_enrollments_api.py
- nessie/jobs/import_sis_student_api.py
- nessie/lib/queries.py
- nessie/models/student.py
https://jira.ets.berkeley.edu/jira/browse/NS-148
> NS-148 Expand student population to ASC+COE

- nessie/api/schedule_controller.py
- tests/test_api/test_schedule_controller.py
https://jira.ets.berkeley.edu/jira/browse/NS-149
> NS-149 API endpoint to update scheduled job args

- nessie/jobs/generate_merged_student_feeds.py
https://jira.ets.berkeley.edu/jira/browse/NS-149
> NS-149 Generate new profile if not present in merged feed job

- nessie/__init__.py
- nessie/jobs/background_job.py
- nessie/models/util.py
QA version of https://github.com/ets-berkeley-edu/nessie/pull/103 and https://github.com/ets-berkeley-edu/nessie/pull/106
> [QA] NS-137 NS-138 Fix advisory lock handling

- nessie/jobs/generate_merged_student_feeds.py
- tox.ini
https://jira.ets.berkeley.edu/jira/browse/NS-149
> NS-149 Merged feed jobs for non-current terms are enrollments only

- nessie/sql_templates/create_boac_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-150
This is far from our highest priority but it was a task which could fit between appointments and meetings, so...
> NS-150 Avoid multiple last_activity_at values for a student

- nessie/externals/asc_athletes_api.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-996
> BOAC-996 ASC API URL transition is complete

- nessie/jobs/create_asc_schema.py
- nessie/jobs/create_coe_schema.py
- nessie/jobs/generate_merged_student_feeds.py
- nessie/jobs/import_asc_athletes.py
- nessie/jobs/import_degree_progress.py
- nessie/jobs/import_sis_enrollments_api.py
- nessie/jobs/import_sis_student_api.py
https://jira.ets.berkeley.edu/jira/browse/NS-154
> NS-154 Replace incremental Redshift inserts with bulk copy from S3

- nessie/jobs/create_asc_schema.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1035
> BOAC-1035 Ignore inactive memberships for otherwise active athletes

- nessie/sql_templates/create_intermediate_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-1003
https://jira.ets.berkeley.edu/jira/browse/BOAC-1004
> BOAC-1003 BOAC-1004 Restore SIS sections which don't map to a Canvas site

- nessie/jobs/create_asc_schema.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1027
The simplest one to test (after Nessie reloads data, anyway).
> BOAC-1027 Fix team name ordering in student summary

- nessie/api/job_controller.py
https://jira.ets.berkeley.edu/jira/browse/NS-162
> NS-162 Let Generate Merged Student Feeds API handle all terms

- nessie/api/job_controller.py
QA version of https://github.com/ets-berkeley-edu/nessie/pull/137
Because a test could require many hours, I'm venturing a QA PR before the change has been validated on Dev. Please do not merge until the team has had a chance to agree.
> [QA] NS-162 Let Generate Merged Student Feeds API handle all terms

- nessie/jobs/scheduling.py
https://jira.ets.berkeley.edu/jira/browse/NS-167
> NS-167 Add CoE students import to scheduled job

- nessie/jobs/scheduling.py
QA version of https://github.com/ets-berkeley-edu/nessie/pull/139
> [QA] NS-167 Add CoE students import to scheduled job

- nessie/api/job_controller.py
- nessie/factory.py
- nessie/jobs/create_metadata_schema.py
- nessie/jobs/create_student_schema.py
- nessie/jobs/generate_asc_profiles.py
- nessie/jobs/scheduling.py
- nessie/sql_templates/create_asc_schema.template.sql
- nessie/sql_templates/create_metadata_schema.template.sql
- nessie/sql_templates/create_student_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-168
QA version of #141.
> NS-168 Generate required schemas on startup if necessary

- nessie/api/job_controller.py
- nessie/jobs/background_job.py
- nessie/jobs/create_asc_schema.py
- nessie/jobs/create_calnet_schema.py
- nessie/jobs/create_canvas_schema.py
- nessie/jobs/create_coe_schema.py
- nessie/jobs/create_metadata_schema.py
- nessie/jobs/create_sis_schema.py
- nessie/jobs/create_student_schema.py
- nessie/jobs/generate_asc_profiles.py
- nessie/jobs/generate_boac_analytics.py
- nessie/jobs/generate_intermediate_tables.py
- nessie/jobs/generate_merged_student_feeds.py
- nessie/jobs/import_asc_athletes.py
- nessie/jobs/import_calnet_data.py
- nessie/jobs/import_degree_progress.py
- nessie/jobs/import_sis_enrollments_api.py
- nessie/jobs/import_sis_student_api.py
- nessie/jobs/resync_canvas_snapshots.py
- nessie/jobs/scheduling.py
- nessie/jobs/sync_canvas_snapshots.py
- nessie/lib/metadata.py
- nessie/lib/queries.py
- nessie/lib/util.py
- nessie/sql_templates/create_metadata_schema.template.sql
- tests/test_api/test_schedule_controller.py
- tests/test_externals/test_redshift.py
- tests/test_jobs/test_create_sis_schema.py
- tests/test_jobs/test_resync_canvas_snapshots.py
https://jira.ets.berkeley.edu/jira/browse/NS-163
https://jira.ets.berkeley.edu/jira/browse/NS-170
> NS-163 Backfill new students; NS-170 Duplicate enrollment row fix

- nessie/api/job_controller.py
- nessie/jobs/background_job.py
- nessie/jobs/create_asc_schema.py
- nessie/jobs/create_calnet_schema.py
- nessie/jobs/create_canvas_schema.py
- nessie/jobs/create_coe_schema.py
- nessie/jobs/create_metadata_schema.py
- nessie/jobs/create_sis_schema.py
- nessie/jobs/create_student_schema.py
- nessie/jobs/generate_asc_profiles.py
- nessie/jobs/generate_boac_analytics.py
- nessie/jobs/generate_intermediate_tables.py
- nessie/jobs/generate_merged_student_feeds.py
- nessie/jobs/import_asc_athletes.py
- nessie/jobs/import_calnet_data.py
- nessie/jobs/import_degree_progress.py
- nessie/jobs/import_sis_enrollments_api.py
- nessie/jobs/import_sis_student_api.py
- nessie/jobs/resync_canvas_snapshots.py
- nessie/jobs/scheduling.py
- nessie/jobs/sync_canvas_snapshots.py
- nessie/lib/metadata.py
- nessie/lib/queries.py
- nessie/lib/util.py
- nessie/sql_templates/create_metadata_schema.template.sql
- tests/test_api/test_schedule_controller.py
- tests/test_externals/test_redshift.py
- tests/test_jobs/test_create_sis_schema.py
- tests/test_jobs/test_resync_canvas_snapshots.py
https://jira.ets.berkeley.edu/jira/browse/NS-163
https://jira.ets.berkeley.edu/jira/browse/NS-170
QA version of #143.
> [QA] NS-163 Backfill new students; NS-170 Duplicate enrollment row fix

- nessie/externals/redshift.py
https://jira.ets.berkeley.edu/jira/browse/NS-171
> NS-171 drop_external_schema seriously means it

- nessie/merged/sis_profile.py
https://jira.ets.berkeley.edu/jira/browse/NS-176
> NS-176 Handle missing academic status in feed merge

- nessie/merged/sis_profile.py
https://jira.ets.berkeley.edu/jira/browse/NS-176
QA version of #146.
> [QA] NS-176 Handle missing academic status in feed merge

- nessie/jobs/create_sis_schema.py
https://jira.ets.berkeley.edu/jira/browse/NS-177
> NS-177 Avoid doubling up SIS Data during term transition

- nessie/externals/sis_degree_progress_api.py
- nessie/jobs/import_degree_progress.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1038
> BOAC-1038 Lack of degree progress information is not an error

- nessie/externals/sis_degree_progress_api.py
- nessie/jobs/import_degree_progress.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1038
QA version of #149.
> [QA] BOAC-1038 Lack of degree progress information is not an error

- nessie/jobs/generate_merged_student_feeds.py
https://jira.ets.berkeley.edu/jira/browse/NS-181
> NS-181 Failed backfills should not kill the entire merged feed job

- nessie/jobs/generate_merged_student_feeds.py
https://jira.ets.berkeley.edu/jira/browse/NS-181
QA version of #153.
> [QA] NS-181 Failed backfills should not kill the entire merged feed job

- nessie/externals/rds.py
- nessie/jobs/create_coe_schema.py
- nessie/jobs/create_rds_indexes.py
- nessie/jobs/generate_asc_profiles.py
- nessie/jobs/generate_merged_student_feeds.py
- nessie/jobs/scheduling.py
- nessie/sql_templates/create_rds_indexes.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-182
QA version of #155.
> [QA] NS-182 RDS storage for index tables

- nessie/jobs/generate_merged_student_feeds.py
- nessie/lib/berkeley.py
https://jira.ets.berkeley.edu/jira/browse/NS-180
> NS-180 Enrolled term credits can be earned before "matriculation"

- nessie/externals/rds.py
- nessie/jobs/create_coe_schema.py
- nessie/jobs/create_rds_indexes.py
- nessie/jobs/generate_asc_profiles.py
- nessie/jobs/generate_merged_student_feeds.py
- nessie/lib/db.py
- nessie/merged/sis_profile.py
https://jira.ets.berkeley.edu/jira/browse/NS-185
> NS-185 Fix duplicate majors, RDS refresh, transaction handling

- nessie/externals/rds.py
- nessie/jobs/create_coe_schema.py
- nessie/jobs/create_rds_indexes.py
- nessie/jobs/generate_asc_profiles.py
- nessie/jobs/generate_merged_student_feeds.py
- nessie/lib/db.py
- nessie/merged/sis_profile.py
https://jira.ets.berkeley.edu/jira/browse/NS-185
QA version of #160.
> [QA] Fix duplicate majors, RDS refresh, transaction handling

- nessie/__init__.py
> NOJIRA, bump to v2.2

- nessie/externals/rds.py
- nessie/externals/redshift.py
- nessie/jobs/generate_merged_student_feeds.py
- nessie/lib/analytics.py
https://jira.ets.berkeley.edu/jira/browse/NS-190
Noisy logs! Hopefully this gives us a good spread of timepoints.
> NS-190 Diagnostic debug logging

- nessie/externals/rds.py
- nessie/externals/redshift.py
- nessie/jobs/generate_merged_student_feeds.py
- nessie/lib/analytics.py
https://jira.ets.berkeley.edu/jira/browse/NS-190
QA version of #164.
> [QA] NS-190 Diagnostic debug logging

- nessie/sql_templates/create_boac_schema.template.sql
... rather than the one which is not.
Just another contributor to https://jira.ets.berkeley.edu/jira/browse/NS-190
> NS-190 Index the assignment_submissions_scores user ID which is queried

- nessie/sql_templates/create_boac_schema.template.sql
QA version of https://github.com/ets-berkeley-edu/nessie/pull/166
> [QA] NS-190 Index the assignment_submissions_scores user ID which is queried

- nessie/api/schedule_controller.py
- tests/test_api/test_schedule_controller.py
https://jira.ets.berkeley.edu/jira/browse/NS-193
> NS-193 Add api/schedule/reload API to restore configured schedule

- nessie/merged/student_terms.py
https://jira.ets.berkeley.edu/jira/browse/NS-197
Follow-up to #169.
> NS-197 No queries needed on empty course id lists

- nessie/externals/rds.py
- nessie/externals/redshift.py
- nessie/jobs/create_coe_schema.py
- nessie/jobs/create_rds_indexes.py
- nessie/jobs/generate_asc_profiles.py
- nessie/jobs/generate_merged_student_feeds.py
https://jira.ets.berkeley.edu/jira/browse/NS-189
The point of this added object layer is that psycopg2 transactions only work if you hold on to a consistent cursor.
> NS-189 Better transaction handling across RDS/Redshift

- nessie/jobs/generate_asc_profiles.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1148
> BOAC-1148 Remove inactive rows for otherwise active athletes

- nessie/jobs/create_coe_schema.py
- nessie/sql_templates/create_coe_schema.template.sql
- nessie/sql_templates/create_rds_indexes.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-98
> NS-98 New COE attributes for the loch

- nessie/__init__.py
Apparently, our release notes need a better pre-flight checklist.
> [QA] NOJIRA, qa branch is now v2.3

- nessie/__init__.py
> NOJIRA, master branch is now v2.4

- nessie/externals/sis_degree_progress_api.py
- nessie/jobs/scheduling.py
- nessie/merged/sis_profile.py
- nessie/sql_templates/create_coe_schema.template.sql
- tests/test_externals/test_sis_degree_progress_api.py
https://jira.ets.berkeley.edu/jira/browse/NS-202
> NS-202 Handle data surprises of all sorts in background jobs

- nessie/externals/sis_degree_progress_api.py
- nessie/jobs/scheduling.py
- nessie/merged/sis_profile.py
- nessie/sql_templates/create_coe_schema.template.sql
- tests/test_externals/test_sis_degree_progress_api.py
https://jira.ets.berkeley.edu/jira/browse/NS-202
QA version of #177.
> [QA] NS-202 Handle data surprises of all sorts in background jobs

- nessie/sql_templates/create_boac_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-205
QA version of #179.
> [QA] NS-205 Guard against duplication in Canvas Data sources

- nessie/merged/sis_profile.py
https://jira.ets.berkeley.edu/jira/browse/NS-203
QA version of #181.
> [QA] NS-203 One more try at malformed Hub feed handling

- nessie/merged/sis_profile.py
https://jira.ets.berkeley.edu/jira/browse/NS-203
> NS-203 One more try at malformed Hub feed handling

- nessie/sql_templates/create_boac_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-142
> NS-142 Incorporate API-derived activity timestamp when appropriate

- nessie/jobs/generate_merged_student_feeds.py
https://jira.ets.berkeley.edu/jira/browse/NS-106
> NS-106 Include term GPA import in new student backfill

- config/default.py
- fixtures/sis_terms_api_2172.json
- nessie/externals/sis_terms_api.py
- tests/test_externals/test_sis_terms_api.py
https://jira.ets.berkeley.edu/jira/browse/NS-206
> NS-206 SIS terms API external connection + fixture

- nessie/lib/analytics.py
- tests/test_lib/test_analytics.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1112
BOAC PR https://github.com/ets-berkeley-edu/boac/pull/830
> BOAC-1112 Remove frozen daysSinceLastActivity value

- nessie/jobs/generate_merged_student_feeds.py
https://jira.ets.berkeley.edu/jira/browse/NS-211
> NS-211 Don't bother with merged feed generation when no Calnet profiles available

- nessie/externals/rds.py
https://jira.ets.berkeley.edu/jira/browse/NS-213
> NS-213 Fix return value for rds.execute

- nessie/__init__.py
> NOJIRA, Nessie master branch is now v2.5

- nessie/api/schedule_controller.py
- nessie/jobs/scheduling.py
https://jira.ets.berkeley.edu/jira/browse/NS-215
Scheduler setup code should run only during app startup.
> NS-215 Separate out schedule initialization from schedule reload

- nessie/api/schedule_controller.py
- nessie/jobs/scheduling.py
https://jira.ets.berkeley.edu/jira/browse/NS-215
QA version of #194.
> [QA] NS-215 Separate out schedule initialization from schedule reload

- README.md
https://jira.ets.berkeley.edu/jira/browse/NS-216
> [QA] NS-216 Trivial change to test deploy pipeline

- README.md
More pipeline testing.
https://jira.ets.berkeley.edu/jira/browse/NS-216
> [QA] NS-216 Another trivial change reverting previous trivial change

- README.md
https://jira.ets.berkeley.edu/jira/browse/NS-216
> [QA] NS-216 One more trivial change for deploy test

- nessie/jobs/generate_merged_student_feeds.py
https://jira.ets.berkeley.edu/jira/browse/NS-219
> NS-219 Merged feeds job: skip upload and verification when no rows generated

- nessie/jobs/generate_merged_student_feeds.py
https://jira.ets.berkeley.edu/jira/browse/NS-219
QA version of #199.
> [QA] NS-219 Merged feeds job: skip upload and verification when no rows generated

- nessie/externals/redshift.py
- nessie/lib/analytics.py
- requirements.txt
- tests/test_externals/test_canvas_api.py
- tests/test_externals/test_sis_degree_progress_api.py
- tests/test_externals/test_sis_enrollments_api.py
- tests/test_externals/test_sis_student_api.py
- tests/test_externals/test_sis_terms_api.py
- tests/test_jobs/test_resync_canvas_snapshots.py
- tests/test_jobs/test_sync_canvas_snapshots.py
- tox.ini
https://jira.ets.berkeley.edu/jira/browse/NS-109
In step with BOAC: https://github.com/ets-berkeley-edu/boac/pull/873
> NS-109, Flask 1.0.2 for Nessie

- nessie/logger.py
https://jira.ets.berkeley.edu/jira/browse/NS-223
Nessie version of https://github.com/ets-berkeley-edu/boac/pull/877.
> NS-223 Call no logger by multiple names

- fixtures/students.sql
- nessie/externals/redshift.py
- nessie/jobs/import_term_gpas.py
- tests/conftest.py
- tests/test_jobs/test_import_term_gpas.py
- tests/test_jobs/test_sync_file_to_s3.py
https://jira.ets.berkeley.edu/jira/browse/NS-224
Test data features recurring characters familiar to fans of the BOAC codebase.
> NS-224 Make ImportTermGpas testable as model for other jobs

- config/default.py
- nessie/externals/boac.py
- nessie/jobs/refresh_boac_cache.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1250
If this looks OK, we'll need to pause before merging so as to make the necessary edit to Dev configuration.
> BOAC-1250 One Nessie can handle multiple BOAC refreshes

- config/default.py
- nessie/externals/dms.py
https://jira.ets.berkeley.edu/jira/browse/LA-521
> LA-521 Utility methods for interacting with DMS endpoints and tasks

- config/default.py
- nessie/externals/lrs.py
https://jira.ets.berkeley.edu/jira/browse/NS-240
> NS-240 Nessie and the LRS can be friends

- nessie/api/job_controller.py
- nessie/jobs/import_lrs_incrementals.py
- nessie/jobs/scheduling.py
https://jira.ets.berkeley.edu/jira/browse/NS-255
- Folder nesting in destination buckets; 
- Whether to truncate the source LRS Aurora is now specificable and by default turned off in the API.
> NS-255 Enhacements to LRS import pipeline

- config/default.py
- nessie/externals/redshift.py
- nessie/jobs/import_lrs_incrementals.py
https://jira.ets.berkeley.edu/jira/browse/NS-260
> NS-260 Caliper import pipeline: unload statements from Redshift to ETL

- nessie/jobs/import_term_gpas.py
https://jira.ets.berkeley.edu/jira/browse/NS-262
> NS-262 Selective refresh for term GPA index in RDS

- nessie/api/job_controller.py
- nessie/jobs/delete_lrs_glue_jobs.py
- nessie/sql_templates/glue_templates/caliper_transforms.py
Background job to delete LRS related glue jobs via an API call. 
https://jira.ets.berkeley.edu/jira/browse/NS-263
> [NS-263] Logic to delete glue jobs via an api call

- nessie/__init__.py
> NOJIRA, bump Nessie master to v2.7

- nessie/jobs/generate_boac_analytics.py
- nessie/jobs/generate_intermediate_tables.py
- nessie/sql_templates/create_boac_schema.template.sql
- nessie/sql_templates/create_intermediate_schema.template.sql
- nessie/sql_templates/create_sis_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-269
> NS-269 Generate section-wide GPA averages

- fixtures/students.sql
- nessie/sql_templates/create_rds_indexes.template.sql
- nessie/sql_templates/create_student_schema.template.sql
- scripts/migrate/20181018-BOAC-1047/rds_increase_units_precision.sql
- scripts/migrate/20181018-BOAC-1047/redshift_increase_units_precision.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-1047
Postgres is easy to migrate, Redshift fussier.
> BOAC-1047 Increase precision of cumulative unit indexes

- nessie/sql_templates/create_canvas_explode_schema_template.sql
Flattened Caliper canvas feeds structure for redshift spectrum. Part of the JIRA
https://jira.ets.berkeley.edu/jira/browse/NS-261
> [NS-261] Canvas Caliper flattened template from the glue process.

- nessie/jobs/import_lrs_incrementals.py
https://jira.ets.berkeley.edu/jira/browse/NS-273
Per discussion with @sandeepmjay, it's this unload to the transient bucket that will be used as an input to Glue, not the datestamped unloads in environment-specific buckets.
> NS-273 Add non-datestamped transient Redshift unload to Caliper import pipeline

- .travis.yml
- nessie/api/metadata_controller.py
- nessie/jobs/import_degree_progress.py
- nessie/lib/metadata.py
- nessie/routes.py
- package.json
- src/App.vue
- src/api/job.ts
- src/components/Header.vue
- src/components/JobMetadata.vue
- src/components/Schedule.vue
- src/main.ts
- src/views/Home.vue
- tests/test_api/test_metadata_controller.py
- vue.config.js
https://jira.ets.berkeley.edu/jira/browse/NS-230
UX still needs work but, for now, I'm concerned with surfacing useful info (eg, job status).
> NS-230, Nessie console shows 'Failures from last sync' and 'Background Jobs of mm/dd/yyyy'

- nessie/api/job_controller.py
https://jira.ets.berkeley.edu/jira/browse/NS-274
> NS-274 Chained Caliper import available through API

- nessie/externals/s3.py
- nessie/jobs/create_coe_schema.py
- nessie/jobs/generate_asc_profiles.py
- nessie/jobs/generate_merged_student_feeds.py
- nessie/jobs/import_asc_athletes.py
- nessie/jobs/import_canvas_enrollments_api.py
- nessie/jobs/import_degree_progress.py
- nessie/jobs/import_sis_enrollments_api.py
- nessie/jobs/import_sis_student_api.py
- nessie/jobs/import_sis_terms_api.py
- nessie/jobs/import_term_gpas.py
- nessie/lib/metadata.py
- nessie/lib/util.py
https://jira.ets.berkeley.edu/jira/browse/NS-281
> NS-281 Build S3-bound TSVs as binary strings for smaller memory footprint

- nessie/jobs/index_enrollments.py
- nessie/lib/queries.py
- nessie/sql_templates/create_rds_indexes.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-1396
> BOAC-1396 Include instructor names in RDS enrolled sections index

- nessie/jobs/import_canvas_enrollments_api.py
https://jira.ets.berkeley.edu/jira/browse/NS-281
There's always one. Follow-up to #257.
> NS-281 Fix typo

- nessie/jobs/generate_merged_student_feeds.py
https://jira.ets.berkeley.edu/jira/browse/NS-287
This is one ugly tangle of code, but I didn't want to get into a full-out refactoring to separate the interwoven strands of term-specific and non-term-specific data updates. Let me know if I'm being too timid.
> NS-287 Students not on CoE & ASC lists should be removed from Nessie

- nessie/lib/analytics.py
- tests/test_lib/test_analytics.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1272
"This time FOR SURE!"
> BOAC-1272 Match the Mean Man to middling students

- nessie/sql_templates/generate_caliper_analytics.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-297
> [NS-297] Included logic to fix course_id parsing anomalies.

- nessie/jobs/transform_lrs_incrementals.py
- nessie/sql_templates/generate_caliper_analytics.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-248
> [NS-248] Add job run response to background jobs metadata table.

- fixtures/students.sql
- nessie/jobs/create_coe_schema.py
- nessie/sql_templates/create_coe_schema.template.sql
- nessie/sql_templates/create_rds_indexes.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-291
> NS-291 Add more CoE student attributes

- nessie/api/admin_controller.py
- package.json
- src/api/job.ts
- src/components/Jobs.vue
- src/main.ts
https://jira.ets.berkeley.edu/jira/browse/NS-231
> NS-231, kick off new Nessie job; required params in path, if necessary

- src/components/Jobs.vue
- src/main.ts
https://jira.ets.berkeley.edu/jira/browse/NS-299
master PR is #272
> [QA] NS-299, 'npm run build-vue' failed due to improper vue-lodash import

- scripts/migrate/20181107-NS-291/rds_add_coe_columns.sql
https://jira.ets.berkeley.edu/jira/browse/NS-291
https://jira.ets.berkeley.edu/jira/browse/NS-300
QA version of #274; follow-up to #268.
> [QA] NS-291 NS-300 Migration script for new COE columns in RDS

- scripts/migrate/20181107-NS-291/rds_add_coe_columns.sql
https://jira.ets.berkeley.edu/jira/browse/NS-291
https://jira.ets.berkeley.edu/jira/browse/NS-300
Follow-up to #268.
> NS-291 NS-300 Migration script for new COE columns in RDS

- nessie/jobs/create_canvas_schema.py
- nessie/lib/util.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1431
Master version of #276.
> BOAC-1431 Allow fallback to yesterday's Canvas data in external schema

- nessie/sql_templates/create_canvas_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/COL-1367
> COL-1367 Add conversation message tables to Canvas external schema

- fixtures/students.sql
- nessie/jobs/create_coe_schema.py
- nessie/sql_templates/create_coe_schema.template.sql
- nessie/sql_templates/create_rds_indexes.template.sql
- scripts/migrate/20181126-BOAC-1445/rds_add_coe_probation_column.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-1445
> BOAC-1445 Add COE probation status column

- .travis.yml
- src/store.ts
https://jira.ets.berkeley.edu/jira/browse/NS-303
Added check to Travis build so we don't fail far along the pipeline.
> NS-303, explicit types in ts files; Travis verifies that ts compiles

- nessie/sql_templates/create_coe_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-1445
Follow-up to #281.
> BOAC-1445 Remove the comma that kills absolutely everything

- fixtures/students.sql
- nessie/jobs/create_coe_schema.py
- nessie/sql_templates/create_coe_schema.template.sql
- nessie/sql_templates/create_rds_indexes.template.sql
- scripts/migrate/20181127-BOAC-1329/rds_add_coe_status_column.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-1329
> BOAC-1329 Add COE status column

- .ebextensions/00_ami.config
https://jira.ets.berkeley.edu/jira/browse/NS-283
> NS-283 Update SSHSourceRestriction for bastion

- nessie/__init__.py
The `qa` branch (v2.8) was cut moments ago.
> NOJIRA, Nessie master branch is now v2.9

- nessie/lib/queries.py
https://jira.ets.berkeley.edu/jira/browse/NS-312
I managed to inject a fatal typo between my original testing and the final PR.
> NS-312 Fix typo in GenerateMergedStudentFeeds SQL

- nessie/sql_templates/create_intermediate_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-314
> NS-314 Avoid duplicates in sis_dropped_classes table

- nessie/jobs/generate_merged_student_feeds.py
https://jira.ets.berkeley.edu/jira/browse/NS-315
Follow-up to #293.
> NS-315 Fix typo (for want of a camel)

- config/default.py
- nessie/jobs/generate_boac_analytics.py
- nessie/sql_templates/create_boac_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-329
> NS-329 Store daily snapshots of BOAC analytics tables for current term

- nessie/jobs/generate_merged_student_feeds.py
- nessie/jobs/import_lrs_incrementals.py
- nessie/jobs/migrate_lrs_incrementals.py
- nessie/lib/analytics.py
https://jira.ets.berkeley.edu/jira/browse/NS-334
> NS-334 Fix multiline logging statements

- nessie/merged/student_terms.py
Master version of https://github.com/ets-berkeley-edu/nessie/pull/308
> NS-339 Do not strip waitlisted enrollments from student feed

- nessie/merged/student_terms.py
https://jira.ets.berkeley.edu/jira/browse/NS-339
QA-first PR for blocker. (Our Dev environment isn't showing Spring 2019 enrollments now anyway.)
> [QA] NS-339 Do not strip waitlisted enrollments from student feed

- config/default.py
https://jira.ets.berkeley.edu/jira/browse/NS-333
Like https://github.com/ets-berkeley-edu/boac/pull/1166, housekeeping only.
> NS-333 Update LDAP host in default config

- fixtures/sis_student_api_1234567890.json
- fixtures/students.sql
- nessie/merged/sis_profile.py
- tests/conftest.py
- tests/test_jobs/test_import_sis_student_api.py
- tests/test_merged/test_sis_profile.py
https://jira.ets.berkeley.edu/jira/browse/NS-340
I think this is the right thing to do for now, but there may need to be a broader discussion about what to do with students who have multiple academic statuses.
> NS-340: falls back on UCBX academic status if no other status

- nessie/sql_templates/create_rds_indexes.template.sql
- scripts/migrate/20190117-NS-346/rds_allow_null_sis_course_title.sql
https://jira.ets.berkeley.edu/jira/browse/NS-346
QA first PR, since this is already breaking production.
> [QA] NS-346 Deal with null SIS Course Titles (new as of Spring 2019)

- nessie/sql_templates/create_rds_indexes.template.sql
- scripts/migrate/20190117-NS-346/rds_allow_null_sis_course_title.sql
Master version of https://github.com/ets-berkeley-edu/nessie/pull/313
> NS-346 Deal with null SIS Course Titles (new as of Spring 2019)

- nessie/lib/queries.py
https://jira.ets.berkeley.edu/jira/browse/NS-347
> NS-347 Disambiguate column names in IndexEnrollments GROUP BY

- config/default.py
- nessie/api/job_controller.py
- nessie/jobs/create_berkeleyx_schema.py
- nessie/sql_templates/create_berkeleyx_schema.template.sql
Create and restore external schemas on transformed Edx data on S3 buckets for BerkeleyX tenants
https://jira.ets.berkeley.edu/jira/browse/NS-349
> [NS-349] Background job and api to Catalog Edx external schemas on Nessie

- nessie/__init__.py
> NOJIRA, bump Nessie version to 2.11

- scripts/suitec/migrate_suitec_database.sh
https://jira.ets.berkeley.edu/jira/browse/COL-1374
After some thrashing, I've ended up with a script intended to be run monthly, which uses a date-based cutoff for events instead of truncating the entire table, and thus doesn't require the app to be paused.
> COL-1374 Nessie swims into the world of SuiteC data management

- src/components/jobs/RunJob.vue
https://jira.ets.berkeley.edu/jira/browse/NS-316
This doesn't yet allow us to run jobs with args, but one step at a time.
> NS-316 Fix front-end error when running Nessie jobs

- src/components/jobs/RunJob.vue
https://jira.ets.berkeley.edu/jira/browse/NS-360
> NS-360 Nessie front end: accept parameters for parameterized jobs

- nessie/api/job_controller.py
- nessie/sql_templates/create_sis_advising_notes_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-358
> NS-358: Fixes note details formatting issues

- nessie/externals/redshift.py
- nessie/sql_templates/create_intermediate_schema.template.sql
- nessie/sql_templates/create_sis_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-221
> NS-221 Track enrollment status changes for current-term primary sections

- nessie/jobs/create_sis_schema.py
- tests/test_jobs/test_create_sis_schema.py
https://jira.ets.berkeley.edu/jira/browse/NS-370
> NS-370 Ensure all expected terms present in SIS data uploads

- config/default.py
- config/test.py
- config/testext.py
- nessie/sql_templates/create_sis_advising_notes_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-371
> NS-371: Provides SIS advising notes internal schema for boac

- config/default.py
- config/test.py
- nessie/jobs/create_coe_schema.py
- nessie/jobs/create_physics_schema.py
- nessie/jobs/generate_asc_profiles.py
- nessie/jobs/generate_merged_student_feeds.py
- nessie/jobs/import_degree_progress.py
- nessie/jobs/import_lrs_incrementals.py
- nessie/jobs/import_sis_student_api.py
- nessie/jobs/import_sis_terms_api.py
- nessie/jobs/import_term_gpas.py
- nessie/jobs/index_enrollments.py
- nessie/lib/util.py
- nessie/sql_templates/create_rds_indexes.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-373
> NS-373 Disambiguate RDS and Redshift schemas

- nessie/sql_templates/create_sis_advising_notes_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-371
> NS-371: Fixes duplicate note rows

- nessie/sql_templates/create_sis_advising_notes_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-374
> NS-374: Adds criteria to select only latest version of a note

- nessie/sql_templates/create_sis_advising_notes_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-375
> NS-375: Adds primary key to advising_notes

- nessie/__init__.py
> NOJIRA, bump Nessie to v2.12 on master

- fixtures/query_advisee_sis_demographics.csv
- nessie/jobs/create_sis_schema.py
- nessie/lib/queries.py
- nessie/sql_templates/create_sis_schema.template.sql
- tests/test_lib/test_queries.py
https://jira.ets.berkeley.edu/jira/browse/NS-304
(This should not be merged until after the QA branch is cut, since it embeds a next-release-Junction dependency.)
> NS-304 Add external table for SIS-provided advisee demographics

- README.md
- fixtures/canvas_data_schema_latest.json
- nessie/api/job_controller.py
- nessie/externals/canvas_data.py
- nessie/externals/redshift.py
- nessie/jobs/refresh_canvas_data_catalog.py
https://jira.ets.berkeley.edu/jira/browse/NS-377
> [NS-377] Automate schema generation for canvas-data by leveraging schema API

- nessie/merged/sis_profile.py
- tests/test_merged/test_sis_profile.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1795
> BOAC-1795 Thread the needle on zero vs. null GPA

- fixtures/query_advisee_sis_demographics.csv
- nessie/jobs/create_sis_schema.py
- nessie/lib/queries.py
- nessie/sql_templates/create_sis_schema.template.sql
- tests/test_lib/test_queries.py
Reverts https://github.com/ets-berkeley-edu/nessie/pull/338 -- there's no reason for Junction to publish until it gains a readership.
> NS-304 Remove SIS Demographics dependency pending functional design

- nessie/externals/s3.py
- nessie/lib/queries.py
- nessie/merged/student_terms.py
https://jira.ets.berkeley.edu/jira/browse/NS-380
> NS-380 Attempt to recover from S3 streaming failures during analytics calculation loop

- nessie/externals/s3.py
- nessie/lib/queries.py
- nessie/merged/student_terms.py
https://jira.ets.berkeley.edu/jira/browse/NS-380
QA version of #346.
I suspect this may be less needed with our larger instance size, but a run on dev doesn't suggest that it introduced any new problems.
> [QA] NS-380 Attempt to recover from S3 streaming failures during analytics calculation loop

- .eslintrc.js
- package-lock.json
- package.json
- src/App.vue
- src/components/Container.vue
- src/components/DisplayError.vue
- src/components/Footer.vue
- src/components/Header.vue
- src/components/jobs/JobStatus.vue
- src/components/jobs/RunJob.vue
- src/router.ts
- src/views/Home.vue
- src/views/Login.vue
- src/views/Schedule.vue
- src/views/Status.vue
https://jira.ets.berkeley.edu/jira/browse/NS-390
Equivalent to changes in https://github.com/ets-berkeley-edu/boac/pull/1311
> NS-390, vue and vuex upgrade; stricter linting

- nessie/api/job_controller.py
https://jira.ets.berkeley.edu/jira/browse/NS-396
> [NS-396] Switching canvas schema creation with an automated schema generation job

- nessie/jobs/refresh_canvas_data_catalog.py
https://jira.ets.berkeley.edu/jira/browse/NS-397
> [NS-397] Added fail safes for canvas daily path generation

- config/default.py
- nessie/jobs/create_sis_advising_notes_schema.py
- nessie/lib/util.py
- nessie/sql_templates/index_sis_advising_notes.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-1858
Meet dblink and to_tsvector! Postgres does it all.
> BOAC-1858 Create full-text advising notes index in RDS

- nessie/externals/calnet.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1768
Identical to change in BOAC-land: https://github.com/ets-berkeley-edu/boac/pull/1344
> BOAC-1768/Nessie: CalNet queries: widen search_base; 'ou' restriction on filter

- package-lock.json
- package.json
https://jira.ets.berkeley.edu/jira/browse/NS-407
> NS-407 Bootstrap upgrade

- config/default.py
- nessie/jobs/create_sis_schema.py
- nessie/lib/berkeley.py
- nessie/lib/queries.py
- tests/test_jobs/test_create_sis_schema.py
https://jira.ets.berkeley.edu/jira/browse/NS-401
> NS-401: Adds future term enrollments to sis schema

- nessie/sql_templates/create_sis_advising_notes_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-413
> NS-413 Pull updated_at from latest version of legacy advising notes

- config/default.py
- nessie/lib/util.py
https://jira.ets.berkeley.edu/jira/browse/NS-421
> NS-421 External advising notes schema reads from dedicated bucket

- nessie/lib/util.py
- nessie/sql_templates/index_sis_advising_notes.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-420
> NS-420 Use environment-specific names for RDS-Redshift dblink

- nessie/sql_templates/index_sis_advising_notes.template.sql
Follow-up to NS-365, which changed two lines and introduced two bugs.
> NS-420 Fix dblink parameters in SQL template

- nessie/sql_templates/create_sis_advising_notes_schema.template.sql
QA-first PR: https://jira.ets.berkeley.edu/jira/browse/NS-435
> [QA] NS-435 Fix hardcoded schema name in template SQL

- nessie/sql_templates/create_sis_advising_notes_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-435
Master-branch version of #368.
> NS-435 Fix hardcoded schema name in template SQL

- nessie/__init__.py
> NOJIRA, Nessie is now v2.13 on master

- nessie/jobs/generate_merged_student_feeds.py
- nessie/lib/analytics.py
- nessie/merged/student_terms.py
- tests/test_lib/test_analytics.py
- tests/test_merged/test_student_terms.py
https://jira.ets.berkeley.edu/jira/browse/NS-429
Once again, we do all the same things in a different order.
> NS-429 Reorganize enrollment-term feed generation for scalability

- nessie/jobs/generate_merged_student_feeds.py
https://jira.ets.berkeley.edu/jira/browse/NS-431
> NS-431 Master-to-worker job dispatch: how about using the right URL

- nessie/api/status_controller.py
- tests/test_api/test_status_controller.py
https://jira.ets.berkeley.edu/jira/browse/NS-443
> NS-443 Use cheaper query for Redshift status check

- nessie/jobs/refresh_canvas_data_catalog.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1959
QA version of #377.
> [QA] BOAC-1959 Report missing S3 data for Canvas external tables

- nessie/jobs/generate_merged_student_feeds.py
- nessie/lib/metadata.py
https://jira.ets.berkeley.edu/jira/browse/NS-449
> NS-449 Merged feeds job: fix final status formatting

- nessie/jobs/refresh_canvas_data_catalog.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1959
> BOAC-1959 Report missing S3 data for Canvas external tables

- nessie/jobs/create_coe_schema.py
- nessie/jobs/generate_asc_profiles.py
- nessie/jobs/import_asc_athletes.py
https://jira.ets.berkeley.edu/jira/browse/NS-437
Since all these jobs run in sequence anyway, we really don't need to be so profligate with the vacuum cleaner.
> NS-437 Remove superfluous vacuum commands

- nessie/models/student_schema.py
https://jira.ets.berkeley.edu/jira/browse/NS-452
> NS-452 Adjust staged enrollment refresh for per-term jobs

- nessie/models/student_schema.py
https://jira.ets.berkeley.edu/jira/browse/NS-452
> NS-452 Fix uncommitted transactions in enrollment terms refresh

- config/default.py
- config/test.py
- nessie/jobs/import_sis_student_api.py
https://jira.ets.berkeley.edu/jira/browse/NS-451
> NS-451 Multithread SIS Student API loop for scalability

- nessie/jobs/generate_merged_enrollment_term.py
https://jira.ets.berkeley.edu/jira/browse/NS-455
Restore a bit of logic that got lost in the refactor.
> NS-455 Ensure analytics data structure for students without assignments

- config/default.py
- nessie/api/job_controller.py
- nessie/jobs/restore_rds_user_privileges.py
- nessie/jobs/restore_redshift_user_privileges.py
- nessie/jobs/scheduling.py
- nessie/lib/util.py
- nessie/sql_templates/restore_rds_user_privileges.template.sql
- nessie/sql_templates/restore_redshift_user_privileges.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-448
> NS-448 Restore app_boa db privileges after nightly schema refresh

- nessie/sql_templates/create_sis_advising_notes_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-457
Python-based function in SQL template takes wonky Pacific time date, converts to UTC and returns in ISO format, and then finally, the built-in converts it to `TIMESTAMPTZ` type.
More info on Redshift + Python UDF:
https://docs.aws.amazon.com/redshift/latest/dg/udf-creating-a-scalar-udf.html
> NS-457, Redshift + Python UDF function: wonky date to UTC, with ISO format, during create schema

- nessie/lib/metadata.py
https://jira.ets.berkeley.edu/jira/browse/NS-462
> NS-462 One redshift per customer

- nessie/__init__.py
> NOJIRA, Nessie master branch is now v2.14

- nessie/externals/calnet.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1917
See description of https://github.com/ets-berkeley-edu/boac/pull/1412
> BOAC-1917, expand LDAP/CalNet query to include 'expired people'

- nessie/externals/calnet.py
https://jira.ets.berkeley.edu/jira/browse/NS-477
> NS-477 Fix exception in LDAP processing

- nessie/jobs/import_term_gpas.py
https://jira.ets.berkeley.edu/jira/browse/NS-492
> NS-492 Do not stop nightly jobs when faced with a new incoming student

- nessie/__init__.py
- nessie/jobs/import_term_gpas.py
QA version of https://github.com/ets-berkeley-edu/nessie/pull/397
> [QA] NS-492 Do not stop nightly jobs when faced with a new incoming student

- nessie/__init__.py
- tox.ini
> NOJIRA, bump Nessie master to v2.15

- config/default.py
- config/test.py
- config/testext.py
- nessie/api/job_controller.py
- nessie/jobs/create_asc_advising_notes_schema.py
- nessie/lib/util.py
- nessie/sql_templates/create_asc_advising_notes_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-499
> NS-499: Adds schemas for ASC advising notes

- config/default.py
- nessie/lib/util.py
- nessie/sql_templates/create_sis_advising_notes_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-422
> NS-422 Restore Redshift-side dblink privileges after notes schema recreation

- nessie/jobs/index_enrollments.py
- nessie/lib/queries.py
- nessie/sql_templates/create_rds_indexes.template.sql
- scripts/migrate/20190429-BOAC-1847/add_subject_area_catalog_id_columns.sql
- tests/conftest.py
Nessie schema changes to faciliate:
https://jira.ets.berkeley.edu/jira/browse/BOAC-1847
https://jira.ets.berkeley.edu/jira/browse/BOAC-1848
plus code tweaks to help with migration and data refresh.
> BOAC-1847 BOAC-1848 Add subject area, catalog id columns to enrolled section index

- nessie/sql_templates/create_l_s_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-520
> NS-520 Make L&S schema available to app_boa user

- fixtures/students.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2167
Minor Nessie-side footnote to https://github.com/ets-berkeley-edu/boac/pull/1494.
> BOAC-2167 Update CoE fixture data

- nessie/__init__.py
> NOJIRA, bump Nessie master branch to v2.16

- nessie/jobs/generate_merged_student_feeds.py
- nessie/sql_templates/create_rds_indexes.template.sql
- nessie/sql_templates/create_student_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2209
> BOAC-2209 Copy more tables into RDS to feed BOAC

- nessie/jobs/generate_merged_student_feeds.py
https://jira.ets.berkeley.edu/jira/browse/NS-538
> NS-538 Fix dblink command execution

- nessie/jobs/generate_merged_enrollment_term.py
- nessie/jobs/generate_merged_student_feeds.py
https://jira.ets.berkeley.edu/jira/browse/NS-538
Something is still not right in Nessie land; investigation continues.
> NS-538 Update dblink config, add error logging

- nessie/sql_templates/create_rds_indexes.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2219
Nessie-side complement to https://github.com/ets-berkeley-edu/boac/pull/1549.
> BOAC-2219 Create student name index table

- nessie/api/schedule_controller.py
- tests/test_api/test_schedule_controller.py
- tests/util.py
https://jira.ets.berkeley.edu/jira/browse/NS-515
> NS-515 API to delete obsolete job definition from schedule

- config/default.py
https://jira.ets.berkeley.edu/jira/browse/NS-527
> NS-527 Change default REDSHIFT_DBLINK_GROUP

- nessie/sql_templates/index_sis_advising_notes.template.sql
- scripts/migrate/20190429-BOAC-1847/create_advising_topic_mappings.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2243
> BOAC-2243 Add note topic translation table for search purposes

- nessie/sql_templates/index_sis_advising_notes.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-546
> NS-546: Fixes SQL error

- nessie/jobs/create_sis_advising_notes_schema.py
- nessie/sql_templates/create_sis_advising_notes_historical_schema.template.sql
- nessie/sql_templates/create_sis_advising_notes_schema.template.sql
- nessie/sql_templates/index_sis_advising_notes.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-488
> NS-488: Adds incremental SIS notes to schema

- nessie/jobs/create_sis_advising_notes_schema.py
- nessie/lib/util.py
- nessie/sql_templates/create_sis_advising_notes_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-488
> NS-488: Adds datestamp to daily path for SIS notes

- package-lock.json
- package.json
https://jira.ets.berkeley.edu/jira/browse/NS-551
> NS-551 Upgrade axios to 0.19

- nessie/__init__.py
Like sands through the hourglass, so are the versions of our lives.
> NOJIRA, Nessie master branch bumped to v2.17

- nessie/jobs/create_sis_advising_notes_schema.py
- nessie/sql_templates/create_sis_advising_notes_schema.template.sql
- nessie/sql_templates/index_sis_advising_notes.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-547
> NS-547: Wraps SIS note indexing in transaction

- nessie/api/schedule_controller.py
https://jira.ets.berkeley.edu/jira/browse/NS-515
> NS-515 Do not require args for DELETE api/schedule/job

- nessie/api/schedule_controller.py
QA version of https://github.com/ets-berkeley-edu/nessie/pull/424
> [QA] NS-515 Do not require args for DELETE api/schedule/job

- nessie/jobs/generate_merged_student_feeds.py
- nessie/sql_templates/create_rds_indexes.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-554
> NS-554 Update student names index when source data updated

- nessie/jobs/generate_merged_student_feeds.py
- nessie/sql_templates/create_rds_indexes.template.sql
> [QA] NS-554 Update student names index when source data updated

- nessie/sql_templates/create_rds_indexes.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-554
Master version of #428.
> NS-554 Don't drop student name index on app startup

- nessie/sql_templates/create_rds_indexes.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-554
> [QA] NS-554 Don't drop student name index on app startup

- nessie/merged/student_terms.py
- tests/test_merged/test_student_terms.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2298
> BOAC-2298 Fix floating point cruft when summing units

- nessie/jobs/scheduling.py
https://jira.ets.berkeley.edu/jira/browse/NS-555
> [QA] NS-555 Rerun IndexEnrollments after student population update

- nessie/jobs/scheduling.py
https://jira.ets.berkeley.edu/jira/browse/NS-555
> NS-555 Rerun IndexEnrollments after student population update

- nessie/merged/student_terms.py
- tests/test_merged/test_student_terms.py
QA version of https://github.com/ets-berkeley-edu/nessie/pull/431
> [QA] BOAC-2298 Fix floating point cruft when summing units

- fixtures/sis_student_api_2345678901.json
- nessie/jobs/generate_merged_student_feeds.py
- nessie/merged/sis_profile.py
- nessie/sql_templates/create_rds_indexes.template.sql
- nessie/sql_templates/create_student_schema.template.sql
- scripts/migrate/20190606-BOAC-1992/rds_pre_deploy_01_add_transfer_graduation_term.sql
- scripts/migrate/20190606-BOAC-1992/redshift_pre_deploy_01_add_transfer_graduation_term.sql
- tests/test_merged/test_sis_profile.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1992
https://jira.ets.berkeley.edu/jira/browse/BOAC-2066
> BOAC-1992 BOAC-2066 Feeds and indexes for transfer, grad term cohort filters

- scripts/migrate/20190606-BOAC-1992/redshift_pre_deploy_01_add_transfer_graduation_term.sql
https://jira.ets.berkeley.edu/jira/browse/NS-558
> NS-558 Staged student schema needs migration too

- nessie/sql_templates/index_asc_advising_notes.template.sql
We only want one row per note.
https://jira.ets.berkeley.edu/jira/browse/BOAC-2238
> BOAC-2238: Squashes rows in ASC note search index

- nessie/jobs/generate_merged_enrollment_term.py
- nessie/jobs/generate_merged_student_feeds.py
- nessie/lib/berkeley.py
- nessie/merged/student_terms.py
- nessie/sql_templates/create_intermediate_schema.template.sql
- tests/test_lib/test_berkeley.py
- tests/test_merged/test_student_terms.py
https://jira.ets.berkeley.edu/jira/browse/NS-562
> NS-562 Restore future-terms processing to GenerateMergedStudentFeeds

- nessie/sql_templates/index_asc_advising_notes.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2238
> BOAC-2238: Allows topicless notes in ASC note search index

- nessie/sql_templates/create_intermediate_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-565
Bug introduced by https://github.com/ets-berkeley-edu/nessie/pull/439
> NS-565 Restore intermediate.course_sections without Canvas sites

- nessie/jobs/create_asc_advising_notes_schema.py
- nessie/sql_templates/create_asc_advising_notes_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-566
This expands the `LOCATION` to include both the historical and incremental folders in la-nessie-*/asc-data/asc-sftp.
> NS-566: Adds incremental ASC notes to schema

- nessie/jobs/create_coe_schema.py
- nessie/jobs/generate_asc_profiles.py
- nessie/sql_templates/create_asc_schema.template.sql
- nessie/sql_templates/create_coe_schema.template.sql
- nessie/sql_templates/create_rds_indexes.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-568
> NS-568 Stash ASC and COE profile feeds in RDS

- nessie/jobs/create_sis_advising_notes_schema.py
- nessie/sql_templates/create_sis_advising_notes_schema.template.sql
- nessie/sql_templates/index_sis_advising_notes.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-569
> NS-569: Restores SIS notes to RDS

- nessie/jobs/create_asc_advising_notes_schema.py
https://jira.ets.berkeley.edu/jira/browse/NS-557
> NS-557 - Makes ASC notes job return a value

- nessie/jobs/create_coe_schema.py
- nessie/jobs/generate_asc_profiles.py
https://jira.ets.berkeley.edu/jira/browse/NS-570
> NS-570 You gotta truncate em afore you load em

- nessie/jobs/import_student_photos.py
https://jira.ets.berkeley.edu/jira/browse/NS-572
> NS-572 A long list of photos not found is just part of life

- nessie/sql_templates/create_intermediate_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-574
> NS-574 Do not let duplicate Canvas accounts break Nessie/BOA

- nessie/sql_templates/index_sis_advising_notes.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-1907
> BOAC-1907 Note search: index legacy category/subcategory if no body

- nessie/__init__.py
> NOJIRA, Nessie master branch is now v2.18

- nessie/externals/calnet.py
- nessie/jobs/create_sis_advising_notes_schema.py
- nessie/jobs/import_calnet_data.py
- nessie/sql_templates/index_sis_advising_notes.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-552
> NS-552 Index advising note authors by name for BOA lookup

- nessie/sql_templates/index_sis_advising_notes.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-552
Follow-up to #454.
> NS-552 Not that id, the other id

- nessie/sql_templates/create_intermediate_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-583
> NS-583 Preserve associated SIS enrollments when filtering out unpublished Canvas sites

- nessie/sql_templates/create_intermediate_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-583
QA version of #456.
> [QA] NS-583 Preserve associated SIS enrollments when filtering out unpublished Canvas sites

- nessie/sql_templates/index_asc_advising_notes.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-580
QA version of #457
> [QA] NS-580: Discards previous versions of an ASC note

- nessie/externals/s3.py
https://jira.ets.berkeley.edu/jira/browse/NS-584
Because "S3 will do that occasionally."
> NS-584 Retry S3 read after a timeout error

- nessie/jobs/import_degree_progress.py
I happened upon what looks like just a copy-paste error.
> NOJIRA: Fixes table name mishap

- nessie/sql_templates/index_asc_advising_notes.template.sql
- nessie/sql_templates/index_sis_advising_notes.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2435
QA version of #463.
> [QA] BOAC-2435 Add timezone info to RDS advising note indexes

- .ebextensions/00_ami.config
https://jira.ets.berkeley.edu/jira/browse/NS-542
> NS-542 Update SSHSourceRestriction

- fixtures/query_advisee_sis_demographics.csv
- nessie/jobs/generate_boac_analytics.py
- nessie/jobs/generate_merged_student_feeds.py
- nessie/lib/queries.py
- nessie/merged/student_demographics.py
- nessie/sql_templates/create_boac_schema.template.sql
- nessie/sql_templates/create_intermediate_schema.template.sql
- nessie/sql_templates/create_rds_indexes.template.sql
- nessie/sql_templates/create_sis_schema.template.sql
- tests/test_merged/test_student_demographics.py
https://jira.ets.berkeley.edu/jira/browse/NS-553
(Junction-Dev has already uploaded the necessary `sis-data/advisees/demographics` data to Nessie-Dev's S3.)
> NS-553 Add non-CoE-specific Gender, Ethnicity data to Loch

- config/default.py
- config/test.py
- config/testext.py
- nessie/api/job_controller.py
- nessie/jobs/create_advisor_schema.py
- nessie/lib/util.py
- nessie/sql_templates/create_advisor_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2350
> BOAC-2350: Creates external schema for advisor data

- nessie/sql_templates/create_advisor_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2352
This is just a first pass and will likely need refinement as BOA requirements become clearer.
> BOAC-2352: Creates internal schema for advisor data

- nessie/__init__.py
`qa` branch was cut moments ago.
> NOJIRA, Nessie is now v2.19 on master branch

- nessie/sql_templates/create_advisor_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2351
Since the story that this Jira belongs to got moved to the next sprint, I'm not planning to submit a QA PR for this.
> BOAC-2351: Adds advisor dept to internal schema

- config/default.py
- nessie/jobs/create_advisor_schema.py
- nessie/lib/util.py
- nessie/sql_templates/create_advisor_schema.template.sql
- nessie/sql_templates/index_advisors.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2381
> BOAC-2381 RDS index table for student-advisor relationships

- nessie/jobs/create_sis_advising_notes_schema.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2464
> BOAC-2464 Include advisors from SIS tables in name index for dropdowns

- nessie/jobs/generate_merged_student_feeds.py
- nessie/lib/queries.py
https://jira.ets.berkeley.edu/jira/browse/NS-610
> NS-610 Fix GenerateMergedStudentFeeds failure

- nessie/merged/sis_profile.py
- tests/test_merged/test_sis_profile.py
https://jira.ets.berkeley.edu/jira/browse/NS-610
> NS-610 Fix another GenerateMergedStudentFeeds failure

- config/default.py
- config/development.py
- nessie/routes.py
- src/api/schedule.ts
- src/views/Schedule.vue
https://jira.ets.berkeley.edu/jira/browse/NS-585
> NS-585 Pause/remove/reload scheduled jobs from web console

- package-lock.json
- package.json
https://jira.ets.berkeley.edu/jira/browse/NS-603
> NS-603 Update lodash dependency

- nessie/__init__.py
With Fall 2019 comes Nessie/BOA v3.0 and an aligned versioning scheme.
> NOJIRA, Nessie is now v3.0 on master branch

- nessie/sql_templates/create_advisor_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2507
> BOAC-2507: Updates advisor_roles logic

- config/default.py
- config/test.py
- config/testext.py
- nessie/externals/s3.py
- nessie/jobs/generate_canvas_caliper_analytics.py
- nessie/lib/metadata.py
- requirements.txt
- tests/util.py
Update smart open to 1.8.3
Use sts to create boto sessions for S3 authentication
Update tests to use mock_sts
update config.py to include APP_ROLE
Parameterize Encryption on S3 to use AES256
https://jira.ets.berkeley.edu/jira/browse/NS-534
> [NS-534]  Use boto sessions for S3 operations. Smart open update to 1.8.3.

- .ebextensions/00_ami.config
- .ebextensions/42_set_default_region.config
- .ebextensions/90_install_inspector.config
parameterizes IAM Instance profile supplied to EC2 instances
Set default region for S3 smart open interactions
Install AWS Inspector agent to track and monitor EC2 instances for resource usage and security monitoring.
https://jira.ets.berkeley.edu/jira/browse/NS-550
> [NS-550] Parameterized Elastic Beanstalk instance profiles. 

- nessie/externals/glue.py
https://jira.ets.berkeley.edu/jira/browse/NS-578
> [NS-578] Glue authentication using sts and boto sessions.

- nessie/externals/dms.py
https://jira.ets.berkeley.edu/jira/browse/NS-579
> [NS-579] Switch DMS authentication to use STS and boto sessions

- config/default.py
- nessie/logger.py
https://jira.ets.berkeley.edu/jira/browse/NS-621
> [NS-621] Downgrade boto log propagation level as debug mode is extra verbose

- nessie/externals/sis_student_api.py
- nessie/merged/sis_profile.py
https://jira.ets.berkeley.edu/jira/browse/NS-625
Because hey, it turns out they happen.
> NS-625 GenerateMergedStudentFeeds should survive no-registration feeds

- nessie/externals/sis_student_api.py
- nessie/merged/sis_profile.py
https://jira.ets.berkeley.edu/jira/browse/NS-627
Fall forward, spring back.
> NS-627 Work around V2 Students API filtering of upcoming registrations

- nessie/sql_templates/create_sis_advising_notes_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2551
> BOAC-2551: Adds column to differentiate between historical and incremental SIS attachments

- nessie/jobs/import_sis_student_api.py
- nessie/merged/sis_profile.py
https://jira.ets.berkeley.edu/jira/browse/NS-625
> NS-625 Deal with SIS Student API errors & empty feed elements

- nessie/sql_templates/create_rds_indexes.template.sql
- nessie/sql_templates/create_student_schema.template.sql
- scripts/migrate/20190729-NS-625/rds_pre_deploy_01_relax_name_constraints.sql
- scripts/migrate/20190729-NS-625/redshift_pre_deploy_01_relax_name_constraints.sql
https://jira.ets.berkeley.edu/jira/browse/NS-625
Since it's possible, it will happen.
> NS-625 Deal with blank student name fields

- nessie/__init__.py
> NOJIRA Master branch is 3.1

- fixtures/sis_student_list_api_v2.json
- nessie/merged/sis_profile.py
- tests/test_merged/test_sis_profile.py
https://jira.ets.berkeley.edu/jira/browse/NS-635
> NS-635 Fix withdrawalCancel in SIS Profile feed

- nessie/sql_templates/create_advisor_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2518
> BOAC-2518 Make Nessie aware of non-advisors with advising note access

- nessie/merged/sis_profile.py
- nessie/merged/sis_profile_v1.py
https://jira.ets.berkeley.edu/jira/browse/NS-637
> NS-637 Avoid Law careers, since they currently break upstream logic

- nessie/sql_templates/index_sis_advising_notes.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-639
> NS-639: Accounts for NULL topics on SIS notes

- nessie/sql_templates/index_sis_advising_notes.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-639
qa version of #505
> [QA] NS-639: Accounts for NULL topics on SIS notes

- config/default.py
- fixtures/sis_student_api_v1_11667051.json
- fixtures/sis_student_api_v1_1234567890.json
- fixtures/sis_student_api_v1_2345678901.json
- fixtures/students.sql
- nessie/externals/sis_student_api.py
- nessie/jobs/generate_merged_student_feeds.py
- nessie/jobs/import_sis_student_api.py
- nessie/lib/queries.py
- nessie/merged/sis_profile.py
- nessie/merged/sis_profile_v1.py
- nessie/sql_templates/create_student_schema.template.sql
- tests/conftest.py
- tests/test_externals/test_sis_student_api.py
- tests/test_jobs/test_import_sis_student_api.py
- tests/test_merged/test_sis_profile.py
- tests/test_merged/test_sis_profile_v1.py
QA version of https://github.com/ets-berkeley-edu/nessie/pull/502 and https://github.com/ets-berkeley-edu/nessie/pull/504
> [QA] NS-637 Fall back to V1 SIS Students API

- nessie/lib/util.py
- nessie/sql_templates/create_intermediate_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-641
> NS-641 Do not try to link SIS sections to pre-CS Canvas sites

- nessie/jobs/scheduling.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2396
> BOAC-2396: Adds E&I notes creation and note author indexing to schedule

- nessie/jobs/create_sis_advising_notes_schema.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2395
> BOAC-2395: Cleans up leftover logging

- nessie/jobs/import_sis_student_api.py
See https://jira.ets.berkeley.edu/jira/browse/NS-642 _if you dare..._
> NS-642 Deal with incoming transfer units in V2 SIS Students API

- nessie/jobs/generate_merged_student_feeds.py
https://jira.ets.berkeley.edu/jira/browse/NS-589
This is part 1 of the work.
> NS-589: Refreshes RDS from Redshift rather than memory

- nessie/jobs/generate_merged_enrollment_term.py
- nessie/jobs/generate_merged_student_feeds.py
- nessie/merged/student_terms.py
- nessie/models/student_schema.py
https://jira.ets.berkeley.edu/jira/browse/NS-589
If this approach works well, we can do something similar with the profile feeds in `generate_student_profile_tables`.
> NS-589: Avoids cluttering memory with excess enrollment terms

- nessie/jobs/generate_merged_student_feeds.py
- nessie/lib/util.py
- nessie/models/student_schema.py
https://jira.ets.berkeley.edu/jira/browse/NS-631
> NS-631: Begins stashing relevant enrollment terms in S3 for future analysis

- nessie/sql_templates/index_sis_advising_notes.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2593
> BOAC-2593 A few more indexes on SIS advising notes

- scripts/migrate/20190819-BOAC-2602/post_deploy_01_create_advising_topic_mappings.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2602
> BOAC-2602 Add topic mappings to SIS advising notes schema

- nessie/lib/berkeley.py
- tests/test_lib/test_berkeley.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2604
See Jira above for UID of student with expected grad term < 2000.
> BOAC-2604, fix Y2K bug in Nessie

- nessie/lib/berkeley.py
- tests/test_lib/test_berkeley.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2604
QA version of PR #520
> [QA] BOAC-2604, fix Y2K bug in Nessie

- config/default.py
- tests/test_jobs/test_import_sis_student_api.py
https://jira.ets.berkeley.edu/jira/browse/NS-661
> NS-661 Prefer V2 SIS Students API to V1 by default

- config/default.py
- nessie/jobs/generate_boac_analytics.py
- nessie/jobs/generate_intermediate_tables.py
- nessie/jobs/generate_merged_student_feeds.py
- nessie/lib/util.py
- nessie/sql_templates/create_boac_schema.template.sql
- nessie/sql_templates/create_intermediate_schema.template.sql
- nessie/sql_templates/create_rds_indexes.template.sql
- nessie/sql_templates/index_advisors.template.sql
- nessie/sql_templates/index_sis_advising_notes.template.sql
- nessie/sql_templates/update_rds_indexes_boac.template.sql
- nessie/sql_templates/update_rds_indexes_sis.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2623
> BOAC-2623 RDS copies of BOA-accessed Redshift tables

- fixtures/sis_student_list_api_v2.json
- nessie/merged/sis_profile.py
- tests/test_merged/test_sis_profile.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2635
> BOAC-2635 Prefer formal descriptions for UC Programs/Colleges

- nessie/sql_templates/update_rds_indexes_boac.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2623
Follow-up to #523.
> BOAC-2623 Commas are hard

- nessie/externals/rds.py
- nessie/externals/redshift.py
- nessie/lib/util.py
- nessie/logger.py
https://jira.ets.berkeley.edu/jira/browse/NS-663
> NS-663 Log cleaner saner SQL

- nessie/jobs/generate_merged_student_feeds.py
- nessie/sql_templates/update_rds_indexes_boac.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2623
Another follow-up to #523.
> BOAC-2623 More SQL fixes

- scripts/migrate/20190819-BOAC-2602/post_deploy_01_create_advising_topic_mappings.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2638
QA version of #528.
> [QA] BOAC-2638 Fix typo in topics join table

- scripts/migrate/20190819-BOAC-2602/post_deploy_01_create_advising_topic_mappings.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2638
> BOAC-2638 Fix typo in topics join table

- nessie/sql_templates/index_sis_advising_notes.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2623
One last (or is it?) follow-up to #523.
> BOAC-2623 More columns for SIS advising note index

- nessie/api/job_controller.py
- nessie/jobs/index_advising_notes.py
- nessie/jobs/scheduling.py
- nessie/sql_templates/index_advising_notes.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-658
> NS-658 Consolidate loch-side advising notes search index

- config/default.py
- nessie/api/job_controller.py
- nessie/jobs/migrate_sis_advising_note_attachments.py
- tests/test_jobs/test_migrate_sis_advising_note_attachments.py
- tests/util.py
> NS-672: Creates job to copy attachments from incremental to historical

- nessie/sql_templates/index_advising_notes.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-679
> NS-679 Fix schema interpolation in SQL template

- config/default.py
- nessie/jobs/migrate_sis_advising_note_attachments.py
- nessie/jobs/scheduling.py
- tests/test_jobs/test_migrate_sis_advising_note_attachments.py
> NS-672: Schedules attachment copy job, allows 'all' or no param

- nessie/jobs/import_sis_student_api_hist_enr.py
- nessie/lib/queries.py
- nessie/sql_templates/create_intermediate_schema.template.sql
- nessie/sql_templates/create_student_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-669
> NS-669 Import SIS Students API feeds for non-current students

- nessie/api/job_controller.py
https://jira.ets.berkeley.edu/jira/browse/NS-669
Should make it easier to do initial testing, anyway.
> NS-669 Add web hook to import SIS Students

- nessie/jobs/import_sis_student_api.py
- nessie/jobs/import_sis_student_api_hist_enr.py
https://jira.ets.berkeley.edu/jira/browse/NS-669
Icky.
> NS-669 Guard against massively swollen Student API feeds

- config/default.py
- config/test.py
- fixtures/sis_student_api_v1_5000000000.json
- fixtures/students.sql
- nessie/api/job_controller.py
- nessie/jobs/chained_import_student_population.py
- nessie/jobs/create_advisee_schema.py
- nessie/jobs/import_non_current_students.py
- nessie/jobs/scheduling.py
- nessie/lib/queries.py
- nessie/lib/util.py
- nessie/sql_templates/create_advisee_schema.template.sql
- tests/conftest.py
- tests/test_jobs/test_import_degree_progress.py
- tests/test_jobs/test_import_registrations.py
- tests/test_jobs/test_import_sis_student_api.py
- tests/test_jobs/test_import_student_photos.py
https://jira.ets.berkeley.edu/jira/browse/NS-671
> NS-671: Includes non-current students on request (from BOA)

- nessie/jobs/migrate_sis_advising_note_attachments.py
- tests/test_jobs/test_migrate_sis_advising_note_attachments.py
> NS-672: Switches to nested date subfolder format

- nessie/api/job_controller.py
- nessie/jobs/generate_merged_hist_enr_feeds.py
- nessie/jobs/import_sis_student_api_hist_enr.py
- nessie/lib/queries.py
- nessie/merged/sis_profile.py
- nessie/merged/student_terms.py
- nessie/models/student_schema.py
- nessie/sql_templates/create_student_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-670
>  NS-670 Generate BOA-friendly feeds for non-advisee student data

- nessie/merged/sis_profile.py
- tests/test_merged/test_sis_profile.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2646
> BOAC-2646 Attempt to parse graduation dates for completed students

- nessie/merged/sis_profile.py
- tests/test_merged/test_sis_profile.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2646
> BOAC-2646 Attempt to parse degrees for students with completed careers

- nessie/jobs/generate_merged_hist_enr_feeds.py
- nessie/sql_templates/update_rds_indexes_hist_enr.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-683
> NS-683 Copy non-advisee summaries to RDS for BOA access

- nessie/jobs/migrate_sis_advising_note_attachments.py
- nessie/lib/metadata.py
- tests/test_jobs/test_migrate_sis_advising_note_attachments.py
> NS-672: Fixes timezone issue and accounts for maintenance days

- nessie/jobs/generate_merged_student_feeds.py
https://jira.ets.berkeley.edu/jira/browse/NS-687
> NS-687 Index active student plans only

- nessie/lib/berkeley.py
- tests/test_lib/test_berkeley.py
https://jira.ets.berkeley.edu/jira/browse/NS-686
> NS-686 Nessie learns the true meaning of Winter

- nessie/jobs/generate_merged_hist_enr_feeds.py
https://jira.ets.berkeley.edu/jira/browse/NS-670
When I started trying to work on the BOA side of things yesterday, I found some goofs in my first attempt at a merged feed.
> NS-670 Fix merged profile structure to match current advisees

- nessie/merged/sis_profile.py
- tests/test_merged/test_sis_profile.py
https://jira.ets.berkeley.edu/jira/browse/NS-685
> NS-685 Teach Degree-parsing code about the pre-CS world

- nessie/jobs/generate_merged_hist_enr_feeds.py
https://jira.ets.berkeley.edu/jira/browse/NS-670
So many ways to break....
> NS-670 Deal with nameless students

- nessie/jobs/generate_merged_hist_enr_feeds.py
https://jira.ets.berkeley.edu/jira/browse/NS-670
> NS-670 Fix running count of non-advisee profiles

- nessie/jobs/migrate_sis_advising_note_attachments.py
- nessie/lib/metadata.py
- tests/test_jobs/test_migrate_sis_advising_note_attachments.py
> NS-672: Changes format of datestamp param

- nessie/jobs/migrate_sis_advising_note_attachments.py
> NS-672: Fixes date range issue re: scheduled job

- nessie/externals/boac.py
- nessie/jobs/import_non_current_students.py
QA version of #565 
https://jira.ets.berkeley.edu/jira/browse/NS-695
> [QA] NS-695: Handles error from BOA API

- nessie/externals/boac.py
- nessie/jobs/import_non_current_students.py
https://jira.ets.berkeley.edu/jira/browse/NS-695
> NS-695: Handles error from BOA API

- nessie/jobs/migrate_sis_advising_note_attachments.py
https://jira.ets.berkeley.edu/jira/browse/NS-698
> NS-698: Fixes return value of scheduled job

- nessie/jobs/migrate_sis_advising_note_attachments.py
https://jira.ets.berkeley.edu/jira/browse/NS-698
QA version of #567
> [QA] NS-698: Fixes return value of scheduled job

- fixtures/sis_student_list_api_v2.json
- nessie/merged/sis_profile.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2739
master PR is #569
> [QA] BOAC-2739, SIS v2 API has varied w.r.t termUnits.type.description; we are tolerant

- fixtures/sis_student_list_api_v2.json
- nessie/merged/sis_profile.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2739
See the Jira for details.
> BOAC-2739, SIS v2 API has varied w.r.t termUnits.type.description; we are tolerant

- nessie/jobs/verify_sis_advising_note_attachments.py
https://jira.ets.berkeley.edu/jira/browse/NS-701
> [NS-701] Variable name fix in the verify job logs to report correct counts

- nessie/jobs/verify_sis_advising_note_attachments.py
https://jira.ets.berkeley.edu/jira/browse/NS-701
Master PR  - https://github.com/ets-berkeley-edu/nessie/pull/572
> [QA_NS-701] Variable name fix in the verify job logs to report correct count.

- nessie/lib/util.py
- nessie/merged/sis_profile.py
- nessie/merged/sis_profile_v1.py
- tests/test_merged/test_sis_profile.py
- tests/test_merged/test_sis_profile_v1.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2753
master PR is #574
> [QA] BOAC-2753, until SISRP-48560 is resolved, we treat 0.5 as 12, the expected min-units per term

- nessie/lib/util.py
https://jira.ets.berkeley.edu/jira/browse/NS-702
Nothingness is a heavy responsibility.
> NS-702 None cannot float

- nessie/lib/util.py
QA version of https://github.com/ets-berkeley-edu/nessie/pull/576
**DO NOT MERGE** unless we get go-ahead from the movers & shakers.
> [QA] NS-702 None cannot float

- nessie/merged/sis_profile.py
- tests/test_merged/test_sis_profile.py
https://jira.ets.berkeley.edu/jira/browse/NS-689
> NS-689 Treat academic plans without status as discontinued

- nessie/lib/queries.py
https://jira.ets.berkeley.edu/jira/browse/NS-707
> NS-707 Non-advisee list should include SIDs with only dropped classes

- nessie/lib/queries.py
https://jira.ets.berkeley.edu/jira/browse/NS-707
Follow-up PR after an uncommitted local change didn't make it to GitHub.
If we get this working, there will be an interim-release QA PR.
> NS-707 Fix parsing of SIS Enrollments for dropped-class students

- nessie/lib/berkeley.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2020
> BOAC-2020 Preserve elective P/NP and S/U grading bases

- fixtures/query_advisee_sis_demographics.csv
- fixtures/sis_student_registrations_demog_api_11667051.json
- fixtures/sis_student_registrations_demog_api_1234567890.json
- fixtures/students.sql
- nessie/externals/sis_student_api.py
- nessie/jobs/generate_boac_analytics.py
- nessie/jobs/generate_merged_student_feeds.py
- nessie/jobs/import_registrations.py
- nessie/lib/queries.py
- nessie/merged/student_demographics.py
- nessie/sql_templates/create_boac_schema.template.sql
- nessie/sql_templates/create_intermediate_schema.template.sql
- nessie/sql_templates/create_rds_indexes.template.sql
- nessie/sql_templates/create_sis_schema.template.sql
- nessie/sql_templates/create_student_schema.template.sql
- tests/test_externals/test_sis_student_api.py
- tests/test_jobs/test_import_registrations.py
- tests/test_merged/test_student_demographics.py
https://jira.ets.berkeley.edu/jira/browse/NS-626
https://jira.ets.berkeley.edu/jira/browse/NS-692
Because this is done through the batched ImportRegistrations, by default it will take about a week for all existing DB-derived demographics data to be replaced by API-derived data.
> NS-626 NS-692 Get visa, other demographics from SIS Students API

- nessie/lib/util.py
- tests/test_jobs/test_migrate_sis_advising_note_attachments.py
- tests/test_lib/test_util.py
Fun with datetimes.
https://jira.ets.berkeley.edu/jira/browse/NS-696
> NS-696: Ignores time when determining dates for attachment sync

- nessie/jobs/generate_merged_hist_enr_feeds.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2782
QA PR to follow if test runs succeed on the dev layer.
> BOAC-2782 Selectively update destination tables in historical enrollments merge

- nessie/jobs/generate_merged_hist_enr_feeds.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2782
QA version of #587.
> [QA] BOAC-2782 Selectively update destination tables in historical enrollments merge

- fixtures/students.sql
- nessie/sql_templates/create_intermediate_schema.template.sql
- nessie/sql_templates/create_rds_indexes.template.sql
- nessie/sql_templates/create_student_schema.template.sql
- scripts/migrate/20191007-NS-682/rds_pre_deploy_01_increase_max_term_gpa.sql
- scripts/migrate/20191007-NS-682/redshift_pre_deploy_01_increase_max_term_gpa.sql
https://jira.ets.berkeley.edu/jira/browse/NS-682
You can't fight the Registrar.
> NS-682 Handle double-digit term GPAs when provided by SIS

- nessie/jobs/generate_merged_student_feeds.py
- nessie/sql_templates/create_rds_indexes.template.sql
- scripts/migrate/20191007-BOAC-2467/rds_pre_deploy_01_index_student_feeds.sql
Three indexes for four features.
https://jira.ets.berkeley.edu/jira/browse/BOAC-2467
https://jira.ets.berkeley.edu/jira/browse/BOAC-2743
https://jira.ets.berkeley.edu/jira/browse/BOAC-2744
https://jira.ets.berkeley.edu/jira/browse/BOAC-2765
> BOAC-2467 BOAC-2743 BOAC-2744 BOAC-2765 New indexes for student feeds

- nessie/jobs/generate_merged_student_feeds.py
- scripts/migrate/20191007-BOAC-2467/rds_pre_deploy_01_index_student_feeds.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2467
> BOAC-2467 Normalize email address index to lowercase

- fixtures/students.sql
- nessie/sql_templates/create_intermediate_schema.template.sql
- nessie/sql_templates/create_rds_indexes.template.sql
- nessie/sql_templates/create_student_schema.template.sql
- scripts/migrate/20191007-NS-682/rds_pre_deploy_01_increase_max_term_gpa.sql
- scripts/migrate/20191007-NS-682/redshift_pre_deploy_01_increase_max_term_gpa.sql
QA version of PR to handle https://jira.ets.berkeley.edu/jira/browse/NS-718 in forthcoming release.
> [QA] NS-682 NS-718 Handle double-digit term GPAs when provided by SIS

- nessie/merged/sis_profile.py
https://jira.ets.berkeley.edu/jira/browse/NS-719
> NS-719 Communicate an erroneously created affiliation more clearly

- config/default.py
- nessie/lib/berkeley.py
- tests/test_lib/test_berkeley.py
https://jira.ets.berkeley.edu/jira/browse/NS-606
> NS-690 Automate term configurations in Nessie

- nessie/api/status_controller.py
- nessie/jobs/create_canvas_schema.py
- nessie/jobs/refresh_canvas_data_catalog.py
- nessie/jobs/resync_canvas_snapshots.py
- nessie/jobs/sync_canvas_snapshots.py
- nessie/lib/berkeley.py
- nessie/lib/util.py
https://jira.ets.berkeley.edu/jira/browse/NS-690
> NS-690 Eliminate remaining dependencies on static term configurations

- fixtures/query_advisee_student_profile_feeds.csv
- nessie/jobs/generate_merged_hist_enr_feeds.py
- nessie/jobs/generate_merged_student_feeds.py
- nessie/lib/queries.py
- nessie/merged/sis_profile.py
- nessie/merged/sis_profile_v1.py
- nessie/sql_templates/create_sis_schema.template.sql
- tests/test_lib/test_queries.py
- tests/test_merged/test_sis_profile.py
- tests/test_merged/test_sis_profile_v1.py
https://jira.ets.berkeley.edu/jira/browse/NS-708
> NS-708 Add intended majors to student profile feeds

- nessie/jobs/import_registrations_hist_enr.py
- nessie/jobs/import_sis_student_api.py
https://jira.ets.berkeley.edu/jira/browse/NS-722
https://jira.ets.berkeley.edu/jira/browse/NS-733
"They're the wrong things that seem right at the time but, even though the right things may seem wrong sometimes, or sometimes the wrong things may be right at the wrong time, or visa versa."
> NS-722 NS-733 Tweak import error handling

- fixtures/query_advisee_student_profile_feeds.csv
- nessie/lib/queries.py
- nessie/merged/sis_profile.py
- nessie/merged/sis_profile_v1.py
- tests/test_lib/test_queries.py
- tests/test_merged/test_sis_profile.py
https://jira.ets.berkeley.edu/jira/browse/NS-736
> NS-736 Deal with multiple intended majors

- nessie/jobs/generate_merged_student_feeds.py
- nessie/sql_templates/create_rds_indexes.template.sql
- scripts/migrate/20191106-BOAC-2743/rds_pre_deploy_01_add_term_gpa_index.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2025
> BOAC-2025 RDS index on term GPA

- nessie/jobs/create_sis_schema.py
- nessie/lib/berkeley.py
- nessie/sql_templates/create_rds_indexes.template.sql
- src/views/Status.vue
- tests/test_jobs/test_create_sis_schema.py
- tests/test_lib/test_berkeley.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3002
> BOAC-3002: Stores automated term configs in RDS

- nessie/__init__.py
> NOJIRA, Nessie is v4 on master branch

- nessie/jobs/create_sis_schema.py
- nessie/lib/berkeley.py
- nessie/sql_templates/create_rds_indexes.template.sql
- tests/test_jobs/test_create_sis_schema.py
- tests/test_lib/test_berkeley.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3002
> BOAC-3002: Drops term IDs from current term index table

- nessie/lib/berkeley.py
- nessie/lib/queries.py
- nessie/merged/student_terms.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3002
> BOAC-3002: Adds temporary logging to troubleshoot GenerateMergedStudentFeeds

- nessie/lib/berkeley.py
- nessie/lib/queries.py
- nessie/merged/student_terms.py
Reverts ets-berkeley-edu/nessie#617
> Revert "BOAC-3002: Adds temporary logging to troubleshoot GenerateMergedStudentFeeds"

- config/default.py
- nessie/externals/redshift.py
- nessie/jobs/generate_merged_hist_enr_feeds.py
- nessie/lib/queries.py
- nessie/merged/student_terms.py
- tests/test_lib/test_queries.py
QA-first PR for https://jira.ets.berkeley.edu/jira/browse/NS-755. Let's see what it does.
> [QA] NS-755 Streaming interface to reduce memory overhead on large Redshift queries

- nessie/lib/queries.py
More on https://jira.ets.berkeley.edu/jira/browse/NS-755.
> [QA] NS-755 SQL fixes

- nessie/lib/queries.py
https://jira.ets.berkeley.edu/jira/browse/NS-755
> NS-755 Another SQL fix

- .ebextensions/00_ami.config
https://jira.ets.berkeley.edu/jira/browse/NS-755
master PR: #623
> [QA] NS-755: Increases instance size to m5.large

- fixtures/sis_student_list_api_v2.json
- nessie/merged/sis_profile.py
- tests/test_merged/test_sis_profile.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3118
> BOAC-3118 Handle alternate email addresses in SIS profile merge

- fixtures/sis_student_list_api_v2.json
- nessie/merged/sis_profile.py
- tests/test_merged/test_sis_profile.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3111
> BOAC-3111 Add declared minors to profile merge

- nessie/externals/calnet.py
- nessie/jobs/create_advisor_schema.py
- nessie/jobs/generate_merged_student_feeds.py
- nessie/jobs/import_calnet_data.py
- nessie/lib/queries.py
- nessie/lib/util.py
- nessie/sql_templates/create_advisor_schema.template.sql
- nessie/sql_templates/create_calnet_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-3109
> BOAC-3109 Include Calnet-derived advisor attributes in student feeds

- nessie/jobs/generate_merged_student_feeds.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3109
> BOAC-3109 Fix KeyError in GenerateMergedStudentFeeds

- nessie/jobs/generate_merged_hist_enr_feeds.py
- nessie/sql_templates/create_student_schema.template.sql
- nessie/sql_templates/update_rds_indexes_hist_enr.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-3108
> BOAC-3108: Indexes names of non-current students

- nessie/jobs/generate_merged_student_feeds.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3109
`itertools._grouper` just isn't a list.
> BOAC-3109 Fix advisor merge into profile feed

- nessie/merged/sis_profile.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3115
> BOAC-3115 Add degree program URL to intended majors

- nessie/lib/queries.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3155
> BOAC-3155 Explicit ordering for per-student advisor feeds

- nessie/merged/sis_profile.py
- tests/test_merged/test_sis_profile.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3155
> BOAC-3155 Sort student plan feeds by plan description

- nessie/jobs/generate_merged_student_feeds.py
- nessie/sql_templates/create_rds_indexes.template.sql
- nessie/sql_templates/create_student_schema.template.sql
- scripts/migrate/20200108-BOAC-3054/rds_pre_deploy_01_add_terms_in_attendance.sql
- scripts/migrate/20200108-BOAC-3054/redshift_pre_deploy_01_add_terms_in_attendance.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-3054
> BOAC-3054: Adds terms_in_attendance to student schema

- nessie/sql_templates/create_rds_indexes.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-3054
> BOAC-3054: Reorders columns to fix terms in attendance bug

- scripts/migrate/20200108-BOAC-3054/rds_pre_deploy_01_add_terms_in_attendance.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-3054
> BOAC-3054: Updates migrate script to new column ordering

- scripts/migrate/20200108-BOAC-3054/rds_pre_deploy_01_add_terms_in_attendance.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-3054
Blargh, one more change.
> BOAC-3054: Spells out column names

- fixtures/students.sql
- nessie/jobs/generate_merged_student_feeds.py
- nessie/merged/sis_profile.py
- nessie/merged/sis_profile_v1.py
- nessie/sql_templates/create_rds_indexes.template.sql
- nessie/sql_templates/create_student_schema.template.sql
- scripts/migrate/20200131-BOAC-3271/rds_pre_deploy_01_add_college.sql
- scripts/migrate/20200131-BOAC-3271/redshift_pre_deploy_01_add_college.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-3271
> BOAC-3271: Adds college to student_majors

- scripts/migrate/20200131-BOAC-3271/rds_pre_deploy_01_add_college.sql
- scripts/migrate/20200131-BOAC-3271/redshift_pre_deploy_01_add_college.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-3271
> BOAC-3271: Fixes migration bugs

- nessie/jobs/generate_merged_student_feeds.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3271
https://jira.ets.berkeley.edu/jira/browse/NS-781
> BOAC-3271: Handles plans with missing programs

- nessie/__init__.py
> [QA] NOJIRA Bump Nessie to 4.3

- nessie/sql_templates/create_rds_indexes.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-779
> NS-779 Ensure that app_boa retains read access to existing RDS tables

- nessie/sql_templates/create_rds_indexes.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-779
> [QA] NS-779 Ensure that app_boa retains read access to existing RDS tables

- nessie/lib/queries.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3382
QA version of #655.
> [QA] BOAC-3382 No nameless advisors in student feeds

- nessie/lib/queries.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3382
> BOAC-3382 No nameless advisors in student feeds

- fixtures/students.sql
- nessie/externals/calnet.py
- nessie/jobs/import_calnet_data.py
- nessie/lib/queries.py
- nessie/sql_templates/create_calnet_schema.template.sql
- nessie/sql_templates/unload_assignment_submissions.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-801
> NS-801 Store CalNet instructor data in the loch

- fixtures/students.sql
- nessie/jobs/generate_merged_hist_enr_feeds.py
- nessie/jobs/generate_merged_student_feeds.py
- nessie/jobs/import_sis_student_api.py
- nessie/jobs/import_sis_student_api_hist_enr.py
- nessie/sql_templates/create_rds_indexes.template.sql
- nessie/sql_templates/create_student_schema.template.sql
- nessie/sql_templates/update_rds_indexes_hist_enr.template.sql
- scripts/migrate/20191007-BOAC-2467/rds_pre_deploy_01_index_academic_career_status.sql
https://jira.ets.berkeley.edu/jira/browse/NS-802
> NS-802 Index historical enrollment profiles, academic career status

- nessie/jobs/generate_merged_hist_enr_feeds.py
- nessie/jobs/generate_merged_student_feeds.py
- nessie/sql_templates/create_rds_indexes.template.sql
- nessie/sql_templates/update_rds_indexes_student_profiles.sql
- nessie/sql_templates/update_rds_indexes_student_profiles_hist_enr.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-802
> NS-802 Unified RDS index for current and non-current students

- nessie/jobs/generate_merged_student_feeds.py
- nessie/sql_templates/create_rds_indexes.template.sql
- nessie/sql_templates/create_student_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2981
> BOAC-2981: Adds intended majors to RDS student schema

- nessie/sql_templates/create_rds_indexes.template.sql
- nessie/sql_templates/update_rds_indexes_student_profiles.sql
- nessie/sql_templates/update_rds_indexes_student_profiles_hist_enr.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-802
> NS-802 Index student degrees on plan and term awarded

- nessie/lib/queries.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3452
> BOAC-3452: Tweaks advisor query to include fake Haas advisor

- nessie/jobs/generate_merged_student_feeds.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3452
Accidentally left this out of my last PR.
> BOAC-3452: Includes advisor SID in student profile feed

- nessie/jobs/generate_merged_student_feeds.py
- nessie/sql_templates/create_rds_indexes.template.sql
- nessie/sql_templates/create_student_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-810
> NS-810: Adds minors to RDS student schema

- nessie/sql_templates/index_sis_advising_notes.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-3489
> BOAC-3489: Separates SIS appointments from SIS notes

- requirements.txt
https://jira.ets.berkeley.edu/jira/browse/NS-808
Housekeeping PR (comes in a limited-edition collector's matched set with 
https://github.com/ets-berkeley-edu/boac/pull/2454).
> NS-808 Update database libraries

- requirements.txt
> Revert NS-808 database upgrades

- nessie/jobs/create_sis_advising_notes_schema.py
- nessie/sql_templates/index_sis_advising_notes.template.sql
- nessie/sql_templates/index_sis_appointment_advisors.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-3489
> BOAC-3489: Creates tables for SIS appointment advisor calnet attributes

- config/default.py
- nessie/lib/util.py
- nessie/sql_templates/create_sis_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-815
> NS-815 Preserve diablo dblink privileges in Redshift student schema

- .ebextensions/40_upgrade_pip.config
- requirements.txt
https://jira.ets.berkeley.edu/jira/browse/NS-812
> NS-812 Update database dependencies

- requirements.txt
https://jira.ets.berkeley.edu/jira/browse/NS-812
> NS-812 Bump SQLAlchemy

- nessie/merged/student_terms.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3492
> BOAC-3492 Don't assign term GPAs to terms with no enrolled units

- nessie/__init__.py
> NOJIRA, Nessie is now v4.7 on master

- package-lock.json
- package.json
https://jira.ets.berkeley.edu/jira/browse/NS-819
> NS-819: Upgrades @vue/cli, forces safe version of minimist

- nessie/lib/queries.py
- nessie/merged/sis_profile.py
- nessie/merged/sis_profile_v1.py
- tests/test_merged/test_sis_profile.py
https://jira.ets.berkeley.edu/jira/browse/NS-851
> [QA] NS-851: Replaces intended majors delimiter with a more peculiar string

- nessie/lib/queries.py
- nessie/merged/sis_profile.py
- nessie/merged/sis_profile_v1.py
- tests/test_merged/test_sis_profile.py
https://jira.ets.berkeley.edu/jira/browse/NS-851
QA PR is #692
> NS-851: Replaces intended majors delimiter with a more peculiar string

- buildspec.yml
https://jira.ets.berkeley.edu/jira/browse/NS-856
> NS-856: Updates buildspec python version

- buildspec.yml
https://jira.ets.berkeley.edu/jira/browse/NS-856
> NS-856 Update buildspec to nodejs 10

- .ebextensions/00_ami.config
https://jira.ets.berkeley.edu/jira/browse/NS-852
> NS-852 Restrict listener on load balancer to TLS 1.2

- package-lock.json
https://jira.ets.berkeley.edu/jira/browse/NS-854
> NS-854 Update Node dependencies

- fixtures/dispatch_import_canvas_api_data.json
- nessie/api/job_controller.py
- nessie/externals/canvas_api.py
- nessie/jobs/import_canvas_api_data.py
- nessie/jobs/import_canvas_grade_change_log.py
- nessie/jobs/import_canvas_gradebook_history.py
- nessie/jobs/scheduling.py
- nessie/lib/metadata.py
- nessie/sql_templates/create_metadata_schema_rds.template.sql
- tests/conftest.py
- tests/test_externals/test_canvas_api.py
- tests/test_jobs/test_import_canvas_api_data.py
- tests/test_jobs/test_import_canvas_grade_change_log.py
- tests/test_jobs/test_import_canvas_gradebook_history.py
https://jira.ets.berkeley.edu/jira/browse/NS-845
> NS-845: Adds job queue for Canvas API jobs

- config/default.py
- nessie/externals/canvas_api.py
https://jira.ets.berkeley.edu/jira/browse/NS-845
> NS-845: Replaces Canvas API token with list of tokens

- nessie/api/job_controller.py
https://jira.ets.berkeley.edu/jira/browse/NS-846
> NS-846: Adds term_id param to Canvas API jobs

- nessie/sql_templates/create_sis_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-864
> NS-864 Add basic attributes table to external SIS schema

- nessie/lib/queries.py
https://jira.ets.berkeley.edu/jira/browse/NS-865
> NS-865 Include basic_attributes table in non-advisee queries

- nessie/externals/calnet.py
- nessie/jobs/index_advising_notes.py
- nessie/sql_templates/create_advising_note_authors.template.sql
- nessie/sql_templates/index_advising_notes.template.sql
- nessie/sql_templates/index_data_science_advising.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-3576
> BOAC-3576: Adds author CalNet data to Data Science notes

- nessie/lib/queries.py
https://jira.ets.berkeley.edu/jira/browse/NS-866
> NS-866 Null SIDs are not OK

- nessie/jobs/import_sis_student_api_hist_enr.py
https://jira.ets.berkeley.edu/jira/browse/NS-866
> NS-866 Adapt to new Student API structure surprises

- nessie/jobs/import_sis_student_api_hist_enr.py
https://jira.ets.berkeley.edu/jira/browse/NS-866
> NS-866 More SIS Student API surprises

- nessie/sql_templates/index_advising_notes.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-870
> NS-870: Populates updated_at on Data Science notes

- nessie/sql_templates/index_advising_notes.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-870
master PR #712
> [QA] NS-870: Populates updated_at on Data Science notes

- nessie/sql_templates/create_data_science_advising_schema.template.sql
- nessie/sql_templates/index_data_science_advising.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-874
> NS-874: Bumps column size to accomodate Data Science note body

- nessie/sql_templates/create_data_science_advising_schema.template.sql
- nessie/sql_templates/index_data_science_advising.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-874
master PR #714
> [QA] NS-874: Bumps column size to accomodate Data Science note body

- nessie/jobs/generate_merged_hist_enr_feeds.py
https://jira.ets.berkeley.edu/jira/browse/NS-873
> NS-873: Plugs the active-inactive enrollment gap

- config/test.py
- nessie/lib/berkeley.py
- tests/test_lib/test_berkeley.py
https://jira.ets.berkeley.edu/jira/browse/NS-862
> NS-862: Expands term ID math to account for past millennia

- nessie/sql_templates/update_rds_indexes_student_profiles_hist_enr.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-876
> NS-876: Accomodates degrees awarded in legacy winter terms

- nessie/externals/calnet.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3580
Nessie version of https://github.com/ets-berkeley-edu/boac/pull/2517.
> BOAC-3580 Remove fallback to deprecated CalNet attributes

- nessie/jobs/generate_merged_student_feeds.py
- nessie/lib/util.py
- nessie/merged/student_demographics.py
- tests/test_merged/test_student_demographics.py
https://jira.ets.berkeley.edu/jira/browse/NS-833
> NS-833: Leverages temp files for storing student profile data sets

- nessie/sql_templates/create_advising_note_authors.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-877
master PR #720
> [QA] NS-877: Removes NOT NULL constraint from note author SID

- .ebextensions/10_install_httpd.config
https://jira.ets.berkeley.edu/jira/browse/NS-848
> NS-848: Configures EC2 access_log LogFormat

- nessie/jobs/chained_import_student_population.py
https://jira.ets.berkeley.edu/jira/browse/NS-883
> NS-883 Refresh external SIS schema before importing current students

- nessie/jobs/create_canvas_api_schema.py
- nessie/jobs/import_canvas_grade_change_log.py
- nessie/jobs/import_canvas_gradebook_history.py
- nessie/lib/util.py
- nessie/sql_templates/create_canvas_api_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-890
> NS-890: Changes Canvas API data S3 location to incremental

- nessie/externals/canvas_api.py
- nessie/externals/s3.py
- nessie/jobs/import_canvas_api_data.py
- nessie/models/student_schema.py
- nessie/sql_templates/create_canvas_api_schema.template.sql
- tests/test_jobs/test_import_canvas_api_data.py
https://jira.ets.berkeley.edu/jira/browse/NS-891
> NS-891: Uses temp files to store gradebook API responses

- fixtures/query_advisee_enrollment_drops.csv
- fixtures/query_advisee_sis_enrollments.csv
- nessie/lib/queries.py
- nessie/merged/student_terms.py
- nessie/sql_templates/create_intermediate_schema.template.sql
- nessie/sql_templates/create_sis_schema.template.sql
- nessie/sql_templates/update_rds_indexes_sis.template.sql
- tests/test_merged/test_student_terms.py
https://jira.ets.berkeley.edu/jira/browse/NS-882
> NS-882 Include instruction mode in enrollment term processing

- nessie/jobs/import_canvas_api_data.py
https://jira.ets.berkeley.edu/jira/browse/NS-897
> NS-897: Adds course ID to Canvas API response

- nessie/sql_templates/create_intermediate_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-882
Follow up to #729.
> NS-882 Can't you hear the thunder, fix a GROUP BY blunder

- nessie/sql_templates/create_intermediate_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-882
One more follow-up to #729.
> NS-882 Add instruction mode to one more table

- nessie/api/job_controller.py
- nessie/jobs/verify_canvas_api_import.py
- nessie/sql_templates/create_canvas_api_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-892
> NS-892: Validates Canvas API import

- fixtures/sis_student_api_v1_11667051.json
- fixtures/sis_student_list_api_v2.json
- nessie/merged/sis_profile.py
- tests/test_merged/test_sis_profile.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3591
> BOAC-3591 Include academic subplans in merged profile

- nessie/api/job_controller.py
- nessie/externals/canvas_api.py
- nessie/externals/s3.py
- nessie/jobs/import_canvas_api_data.py
- nessie/jobs/import_canvas_grade_change_log.py
- nessie/jobs/import_canvas_gradebook_history.py
- nessie/lib/metadata.py
- nessie/sql_templates/create_canvas_api_schema.template.sql
- tests/test_jobs/test_import_canvas_api_data.py
https://jira.ets.berkeley.edu/jira/browse/NS-891
> NS-891: Streams Canvas API data to S3, one page at a time

- nessie/jobs/generate_merged_student_feeds.py
- nessie/sql_templates/create_rds_indexes.template.sql
- nessie/sql_templates/create_sis_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-3410
> BOAC-3410 Add academic standing tables to Redshift/RDS

- nessie/jobs/generate_merged_student_feeds.py
- nessie/sql_templates/create_student_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-908
> NS-908 Add Redshift internal schema for academic status

- nessie/api/job_controller.py
- nessie/jobs/create_canvas_api_schema.py
- nessie/jobs/transform_canvas_api_data.py
- nessie/lib/util.py
- nessie/sql_templates/create_canvas_api_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-907
> NS-907: Adds job to transform Canvas API data into multiline JSON

- nessie/sql_templates/create_rds_indexes.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-908
> NS-908 Update RDS index for academic standing

- nessie/api/user_controller.py
- nessie/models/user.py
- nessie/routes.py
- requirements.txt
- tox.ini
https://jira.ets.berkeley.edu/jira/browse/NS-913
As performed in https://github.com/ets-berkeley-edu/boac/pull/2532
> NS-913, update py-deps; flask-login user_callback dropped

- nessie/jobs/transform_canvas_api_data.py
https://jira.ets.berkeley.edu/jira/browse/NS-907
> NS-907: Updates Canvas grades transform job to skip repeats

- .eslintrc.js
- package-lock.json
- package.json
- requirements.txt
- src/App.vue
- src/components/Header.vue
- src/components/jobs/JobStatus.vue
- tox.ini
https://jira.ets.berkeley.edu/jira/browse/NS-941
> NS-941, after qa branch cut: update package/py deps

- .eslintrc.js
- src/App.vue
- src/api/job.ts
- src/api/schedule.ts
- src/api/status.ts
- src/api/user.ts
- src/components/Container.vue
- src/components/DisplayError.vue
- src/components/Footer.vue
- src/components/Header.vue
- src/components/jobs/JobStatus.vue
- src/components/jobs/RunJob.vue
- src/main.ts
- src/mixins/Context.vue
- src/router.ts
- src/store/index.ts
- src/store/modules/context.ts
- src/store/modules/schedule.ts
- src/store/modules/user.ts
- src/views/Home.vue
- src/views/Login.vue
- src/views/Schedule.vue
- src/views/Status.vue
https://jira.ets.berkeley.edu/jira/browse/NS-941
A bit Pythonic, you might say.
> NS-941, eslint 'no semicolons' rule (Vue files, javascript/typescript)

- nessie/api/job_controller.py
- nessie/externals/s3.py
- nessie/jobs/import_piazza_api_data.py
- nessie/jobs/transform_piazza_api_data.py
- nessie/lib/util.py
https://jira.ets.berkeley.edu/jira/browse/NS-939
> NS-939, initial commit of piazza nessie import and transform jobs

- nessie/jobs/import_piazza_api_data.py
- nessie/jobs/transform_piazza_api_data.py
No significant operational changes.
* fixed job queue messages (some fields were not filled out correctly)
* fixed log messages (some infos were errors, and vice versa)
* slight improvements to job stats gathered.
* cruft removed, minor refactoring for clarity.
> NS-946: refactoring of piazza nessie jobs, correct logging issues

- nessie/sql_templates/create_edl_sis_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-932
> NS-932: Fixes data format issues

- config/default.py
- nessie/jobs/scheduling.py
- Add Piazza Import and Transform as a "chained job"
- Bring default.py up-to-date
> NS-948, add scheduling for piazza jobs, update default.py

- config/default.py
- nessie/jobs/create_edl_sis_schema.py
- nessie/lib/queries.py
- nessie/lib/util.py
- nessie/sql_templates/create_edl_sis_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-957
> NS-957: Slips EDL degree progress into the student profile

- nessie/lib/queries.py
https://jira.ets.berkeley.edu/jira/browse/NS-960
Also reorganized column aliases to reduce confusion.
> NS-960: Limits length of SIDs in accordance with SIS API constraints

- nessie/api/job_controller.py
- nessie/jobs/import_piazza_api_data.py
- nessie/jobs/transform_piazza_api_data.py
Parameter checking needed a bit of improvement; and job queue messages look better!
> NS-976, improve job queue messages, minor bulletproofing for Piazza jobs

- nessie/lib/http.py
https://jira.ets.berkeley.edu/jira/browse/NS-940
> NS-940: Prevents logging of auth params when API call fails

- nessie/lib/util.py
...as opposed to trying to make this work purely through scheduling.
> NS-976, use 'yesterday' as the date for 'latest' in piazza jobs

- package-lock.json
https://jira.ets.berkeley.edu/jira/browse/NS-988
> NS-988: updates node-fetch and serialize-javascript

- config/default.py
- nessie/jobs/create_edl_sis_schema.py
- nessie/lib/util.py
- nessie/sql_templates/create_edl_sis_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-990
master PR is #766
> [QA] NS-990: Automates creating external schema from EDL catalog

- config/default.py
- nessie/jobs/create_edl_sis_schema.py
- nessie/lib/util.py
- nessie/sql_templates/create_edl_sis_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-990
> NS-990: Automates creating external schema from EDL catalog

- package-lock.json
- package.json
https://jira.ets.berkeley.edu/jira/browse/NS-986
> NS-986: Updates node-forge (via selfsigned)

- nessie/merged/sis_profile.py
- tests/test_merged/test_sis_profile.py
https://jira.ets.berkeley.edu/jira/browse/NS-925
> NS-925: Adds awarded minors to student profile

- .ebextensions/60_secure_sshd.config
- .ebextensions/99_delayed_script.config
Applying CIS Benchmark recommendations in sshd_config https://jira.ets.berkeley.edu/jira/browse/NS-968
> Adding new 99_delayed_script.config and 60_secure_sshd.config for NS-968

- nessie/jobs/scheduling.py
https://jira.ets.berkeley.edu/jira/browse/NS-994
> NS-994: Schedules CreateEdlSisSchema

- nessie/jobs/migrate_sis_advising_note_attachments.py
- nessie/jobs/verify_sis_advising_note_attachments.py
- nessie/lib/util.py
- nessie/sql_templates/create_sis_advising_notes_schema.template.sql
- tests/conftest.py
- tests/test_jobs/test_migrate_sis_advising_note_attachments.py
- tests/test_jobs/test_verify_sis_advising_note_attachments.py
https://jira.ets.berkeley.edu/jira/browse/NS-993
> NS-993: Enforces naming convention for wayward SIS note attachments

- nessie/externals/s3.py
https://jira.ets.berkeley.edu/jira/browse/NS-1027
> NS-1027 Save memory with tempfiles on JSON upload to S3

- nessie/externals/s3.py
https://jira.ets.berkeley.edu/jira/browse/NS-1027
QA version of #777.
> [QA] NS-1027 Save memory with tempfiles on JSON upload to S3

- nessie/__init__.py
In anticipation of patch release.
> [QA] NOJIRA 4.10.1 patch version bump

- nessie/jobs/import_canvas_enrollments_api.py
> NS-1019 Use temporary external schema instead of COPY for large Redshift load

- nessie/jobs/import_canvas_enrollments_api.py
> [QA] NS-1019 Use temporary external schema instead of COPY for large Redshift load

- nessie/externals/s3.py
https://jira.ets.berkeley.edu/jira/browse/NS-1027
> NS-1027 Sort out read/write modes for JSON tempfiles

- nessie/externals/s3.py
https://jira.ets.berkeley.edu/jira/browse/NS-1027
QA version of #782.
I don’t plan to make a habit of these weekend/vacation PRs, but I’d like Nessie to have a few runs with this code over the break.
> [QA] NS-1027 Sort out read/write modes for JSON tempfiles

- nessie/jobs/import_canvas_enrollments_api.py
> NS-1019 Once external schemas are in play, you gotta treat it like a DDL

- nessie/jobs/import_canvas_enrollments_api.py
QA version of #784.
As with #783, would like to give Nessie an opportunity to chew on this over the break.
> [QA] NS-1019 Once external schemas are in play, you gotta treat it like a DDL

- nessie/jobs/import_canvas_enrollments_api.py
> NS-1019 Adjust syntax for external schema

- nessie/jobs/import_canvas_enrollments_api.py
QA version of #786, follow-up to #785.
> [QA] NS-1019 Adjust syntax for external schema

- nessie/jobs/create_oua_schema.py
https://jira.ets.berkeley.edu/jira/browse/NS-1032
> NS-1032, CreateOUASchema will not raise error if 'no OUA files found'

- nessie/jobs/create_oua_schema.py
https://jira.ets.berkeley.edu/jira/browse/NS-1032
master PR is #789
> [QA] NS-1032, CreateOUASchema will not raise error if 'no OUA files found'

- nessie/jobs/scheduling.py
- tests/test_api/test_schedule_controller.py
https://jira.ets.berkeley.edu/jira/browse/NS-1013
> NS-1013 Refresh SIS schema before generating intermediate tables

- nessie/jobs/scheduling.py
- tests/test_api/test_schedule_controller.py
https://jira.ets.berkeley.edu/jira/browse/NS-1013
QA version of #791.
> [QA] NS-1013 Refresh SIS schema before generating intermediate tables

- nessie/jobs/generate_merged_student_feeds.py
- nessie/sql_templates/create_rds_indexes.template.sql
- scripts/migrate/20201222-NS-996/rds_pre_deploy_01_add_epn_grading_option.sql
https://jira.ets.berkeley.edu/jira/browse/NS-996
> NS-996: adds EPN grade option flag to enrollment term index

- package-lock.json
- package.json
https://jira.ets.berkeley.edu/jira/browse/NS-1037
> NS-1037 Bump axios version

- nessie/jobs/import_canvas_enrollments_api.py
- nessie/jobs/import_degree_progress.py
- tests/test_jobs/test_import_degree_progress.py
https://jira.ets.berkeley.edu/jira/browse/NS-1041
https://jira.ets.berkeley.edu/jira/browse/NS-1029
The master PR was #794
> [QA] NS-1041 / NS-1029, ImportDegreeProgress: Use temp external schema rather than a COPY command

- nessie/__init__.py
> [QA] Nessie qa branch bumped to v4.10.2

- nessie/jobs/create_sis_terms_schema.py
- tests/test_jobs/test_create_sis_terms_schema.py
https://jira.ets.berkeley.edu/jira/browse/NS-888
> NS-888 Adjust term calendaring to catch advance enrollment periods

- nessie/sql_templates/create_edl_sis_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1052
> NS-1052: Adds profiles, majors, and minors index tables

- nessie/jobs/create_edl_schema.py
- nessie/jobs/generate_merged_student_feeds.py
- nessie/sql_templates/create_edl_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1053
> NS-1053: Builds json feeds, RDS indexes with acad plan data

- nessie/api/status_controller.py
- nessie/jobs/create_edl_schema.py
- nessie/jobs/import_registrations_hist_enr.py
- nessie/lib/berkeley.py
- nessie/lib/queries.py
- nessie/sql_templates/create_edl_schema.template.sql
- tests/test_api/test_job_controller.py
https://jira.ets.berkeley.edu/jira/browse/NS-1076
EDL query results are shoe-horned into existing design pattern: put tsv in S3 prior to populating `hist_enr_term_gpas` and `hist_enr_last_registrations`. There are a handful of TODOs.
> NS-1076, ImportRegistrationsHistEnr queries edl_ext.student_registration_term_data if feature_flag

- src/mixins/Context.vue
- src/store/modules/context.ts
- src/views/Status.vue
https://jira.ets.berkeley.edu/jira/browse/NS-1076
Follow up to PR #810
> NS-1076, show EDL-feature-flag setting on /status page

- nessie/jobs/import_registrations_hist_enr.py
- nessie/lib/berkeley.py
- nessie/merged/sis_profile.py
https://jira.ets.berkeley.edu/jira/browse/NS-1076
> NS-1076, minor fixes in ImportRegistrationsHistEnr

- nessie/sql_templates/create_edl_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1023
> NS-1023: Adds demographic data to Redshift EDL

- nessie/lib/queries.py
- src/views/Status.vue
https://jira.ets.berkeley.edu/jira/browse/NS-1045
> NS-1045, SQL and the importance of commas

- nessie/jobs/import_registrations_hist_enr.py
- src/router.ts
- src/views/Status.vue
https://jira.ets.berkeley.edu/jira/browse/NS-1045
We hit another memory issue in nessie-dev. Having EDL respect batch-mode is fine, the transaction is fast. This PR includes column name fixes and minor front-end tweak. (Job ran successfully locally.)
> NS-1045, import_registrations_hist_enr: Respect batch mode when querying EDL

- nessie/jobs/abstract/abstract_registrations_job.py
- nessie/jobs/import_registrations.py
- nessie/jobs/import_registrations_hist_enr.py
https://jira.ets.berkeley.edu/jira/browse/NS-1046
The two `ImportRegistrations` jobs have same logic.
> NS-1046, abstract_registrations_job for big chunk of shared logic (EDL/student_api)

- nessie/sql_templates/create_edl_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1049
> NS-1049 EDL-sourced course and enrollment tables (work in progress)

- nessie/externals/redshift.py
- nessie/lib/queries.py
- nessie/sql_templates/create_edl_schema.template.sql
- tests/test_jobs/test_import_degree_progress.py
- tests/test_jobs/test_import_registrations.py
https://jira.ets.berkeley.edu/jira/browse/NS-1081
See description of Jira above.
> NS-1081, student_term_gpas EDL table; TODO: equivalent of 'sis_profiles'?

- nessie/sql_templates/create_edl_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1047
> NS-1047 EDL equivalent to SISEDO term GPA table

- nessie/jobs/generate_intermediate_tables.py
https://jira.ets.berkeley.edu/jira/browse/NS-1051
> NS-1051 EDL schema can be swapped in as intermediate schema source

- nessie/jobs/import_sis_student_api_hist_enr.py
https://jira.ets.berkeley.edu/jira/browse/NS-1085
Missed a table ref in work of PR #832
> NS-1085, ImportSisStudentApiHistEnr toggle per EDL flag: student_schema_table('sis_profiles_hist_enr')

- nessie/sql_templates/create_edl_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1086
> NS-1086 Cast varchar EDL flag to boolean

- nessie/api/admin_controller.py
- src/api/status.ts
- src/views/Home.vue
https://jira.ets.berkeley.edu/jira/browse/NS-1087
Kick off a job -> random xkcd.
> NS-1087, confirmation in UI when user kicks off a Nessie job

- nessie/jobs/background_job.py
- nessie/jobs/create_sis_schema.py
https://jira.ets.berkeley.edu/jira/browse/NS-1088
> NS-1088, tolerate zero count in certain legacy student_schema tables if feature_flag_edl

- nessie/sql_templates/create_intermediate_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1092
> NS-1092 Stricter casting in intermediate schema to fit EDL source

- nessie/jobs/abstract/abstract_registrations_job.py
- nessie/lib/berkeley.py
https://jira.ets.berkeley.edu/jira/browse/NS-1095
> NS-1095, json.dumps to put valid JSON (EDL) in tsv

- nessie/sql_templates/create_intermediate_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1092
> NS-1092 Yet more column casting

- nessie/lib/berkeley.py
- nessie/lib/queries.py
https://jira.ets.berkeley.edu/jira/browse/NS-1080
> NS-1080, more EDL column matching w.r.t student reg data

- nessie/api/admin_controller.py
- package.json
- src/views/Home.vue
https://jira.ets.berkeley.edu/jira/browse/NS-1098
I've also added a 'duration' column.
> NS-1098, jobs that do not finish cleanly are identified (red icon) in UI

- nessie/externals/b_connected.py
https://jira.ets.berkeley.edu/jira/browse/NS-1091
> NS-1091, send job-failure alert if and only if EMAIL_FEATURE_ENABLED

- nessie/lib/berkeley.py
https://jira.ets.berkeley.edu/jira/browse/NS-1099
> NS-1099, do not jsonify Decimal objects cuz it won't work

- nessie/lib/berkeley.py
- src/views/Home.vue
https://jira.ets.berkeley.edu/jira/browse/NS-1099
> NS-1099, Decimal(0.0) is falsey so 'not None' is the check

- fixtures/redshift_schema_edl.sql
- fixtures/redshift_schema_student_metadata.sql
- nessie/jobs/create_edl_schema.py
- nessie/lib/queries.py
- nessie/merged/student_demographics.py
- nessie/sql_templates/create_edl_schema.template.sql
- tests/test_jobs/test_create_edl_schema.py
https://jira.ets.berkeley.edu/jira/browse/NS-1023
> NS-1023: Adds demographics feeds to EDL schema

- nessie/lib/berkeley.py
- nessie/lib/queries.py
https://jira.ets.berkeley.edu/jira/browse/NS-1106
> NS-1106, couple fixes for edl_registration_to_json: term.academicYear, termUnits

- nessie/models/student_schema_manager.py
- nessie/sql_templates/create_edl_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1107
> NS-1107, student_profile_index_hist_enr and student_profiles_hist_enr for EDL student schema

- nessie/api/status_controller.py
- nessie/externals/redshift.py
- nessie/jobs/create_edl_schema.py
- nessie/routes.py
https://jira.ets.berkeley.edu/jira/browse/NS-1108
Impacts `/api/ping` context only and we continue to log warnings and errors.
> NS-1108, reduce '/api/ping' related noise in Nessie log

- nessie/api/analyze_edl_controller.py
- nessie/lib/berkeley.py
- nessie/merged/student_terms.py
https://jira.ets.berkeley.edu/jira/browse/NS-1110
Includes new 'analyze_edl' endpoint: `/api/analyze_edl/term_gpa/<term_id>/<sid>`
> NS-1110, student_terms.merge_enrollment(): float(value) before jsonify on Decimal

- nessie/api/analyze_edl_controller.py
- nessie/jobs/import_sis_student_api.py
https://jira.ets.berkeley.edu/jira/browse/NS-1042
Includes added `/api/analyze_edl/student/<sid>` endpoint.
> NS-1042, ImportSisStudentApi job: feature_flag aware and JSON structure (mock data) which EDL must populate

- src/views/Home.vue
https://jira.ets.berkeley.edu/jira/browse/NS-1087
> NS-1087, very minor cleanup in Nessie UI

- nessie/lib/queries.py
- nessie/sql_templates/create_edl_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1089
> NS-1089: Creates empty tables to avoid job failure

- nessie/sql_templates/create_sis_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1119
> NS-1119: Grants dblink SELECT on sis_data_ext_*

- nessie/jobs/generate_merged_student_feeds.py
https://jira.ets.berkeley.edu/jira/browse/NS-1119
> NS-1119: Corrects schema name in GenerateMergedStudentFeeds

- nessie/jobs/generate_merged_student_feeds.py
https://jira.ets.berkeley.edu/jira/browse/NS-1121
> NS-1121: Corrects schema mixup impacting academic_standing

- nessie/api/job_controller.py
- nessie/jobs/import_piazza_api_data.py
- nessie/jobs/scheduling.py
- nessie/jobs/transform_piazza_api_data.py
Import now figures out whether to fetch daily or monthly archive. Transform will become its own scheduled job, no longer chained with Import.
> NS-1039: refactor piazza import and transform jobs to handle monthly archive

- config/default.py
- nessie/jobs/create_asc_advising_notes_schema.py
- nessie/sql_templates/create_asc_advising_notes_schema.template.sql
- nessie/sql_templates/index_asc_advising_notes.template.sql
First pass at the Nessie portion of https://jira.ets.berkeley.edu/jira/browse/BOAC-3987.
> BOAC-3987 Process subject and body of ASC notes after cutoff date

- config/default.py
- nessie/jobs/create_asc_advising_notes_schema.py
- nessie/sql_templates/create_asc_advising_notes_schema.template.sql
- nessie/sql_templates/index_asc_advising_notes.template.sql
This reverts commit 8aa68e861fd2150891ffe465bd23f6a70baead1a.
Changes in PR #865 will just break the ASC note jobs until the source data is cleaned up.
> Revert "BOAC-3987 Process subject and body of ASC notes after cutoff date"

- nessie/jobs/scheduling.py
... so the job scheduler will schedule it. Also tidy up invocation of both Import and Transform jobs.
> NS-1142: add job id to Piazza Transform job

- nessie/jobs/scheduling.py
https://jira.ets.berkeley.edu/jira/browse/NS-1144
Master PR:
https://github.com/ets-berkeley-edu/nessie/pull/871
> [QA] NS-1144: use correct method (schedule_job) for Piazza jobs

- nessie/sql_templates/create_asc_advising_notes_schema.template.sql
- nessie/sql_templates/index_asc_advising_notes.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-3987
Get some of the process in place while waiting on resolution of source data issues.
> BOAC-3987 Parse subject and body from ASC notes where available

- nessie/sql_templates/create_asc_advising_notes_schema.template.sql
- nessie/sql_templates/index_asc_advising_notes.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-3987
Follow-up to #873.
> BOAC-3987 Follow-ups for ASC advising note parsing

- nessie/sql_templates/index_asc_advising_notes.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-3987
One more.
> BOAC-3987 Fix column mismatch in ASC advising note indexing

- nessie/sql_templates/index_advising_notes.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-3995
> BOAC-3995 Add ASC notes to search snippet indexing

- nessie/sql_templates/create_asc_advising_notes_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-4043
> BOAC-4043 Preserve topics in older ASC advising notes

- nessie/sql_templates/create_asc_advising_notes_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-4043
Boo-boo in #877.
> BOAC-4043 Fix bad table reference

- nessie/jobs/import_registrations_hist_enr.py
https://jira.ets.berkeley.edu/jira/browse/NS-1146
> NS-1146 Restore status logging on ImportRegistrationsHistEnr job

- nessie/api/job_controller.py
- nessie/lib/util.py
... and not on the last day of the month.
The timing is alas just a bit complicated!
> NS-1151: fetch piazza 'monthly' archive on the 1st day of the month

- requirements.txt
https://jira.ets.berkeley.edu/jira/browse/NS-1152
> NS-1152, py updates: Flask/Werkzeug and other minor bumps

- nessie/api/job_controller.py
Still trying to make this work! It is hard to test -- end-of-month condition only happens once a month, and we do have to access the Piazza API to see that it really works, so the correct archive has to be there at the correct time.
> NS-1151: fetch the piazza monthly archive at start of month

- nessie/sql_templates/index_advisors.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-3976
Prep work for automating degree progress permissions
> BOAC-3976: Adds advisor_attributes to RDS schema

- nessie/jobs/import_registrations_hist_enr.py
- nessie/lib/queries.py
https://jira.ets.berkeley.edu/jira/browse/NS-1155
> NS-1155 Query student API only for non-advisees with student affiliation

- nessie/jobs/import_registrations_hist_enr.py
- nessie/jobs/import_sis_student_api_hist_enr.py
- nessie/lib/queries.py
https://jira.ets.berkeley.edu/jira/browse/NS-1155
Follow-up to #891: logging fixes, screen out alumni and inactive person_type values.
> NS-1155 Follow-up to student API inactive screen-out

- package-lock.json
https://jira.ets.berkeley.edu/jira/browse/NS-1161
> NS-1161 npm package updates

- nessie/jobs/scheduling.py
- tests/test_api/test_schedule_controller.py
https://jira.ets.berkeley.edu/jira/browse/NS-1158
> NS-1158 Remove LRS/Caliper jobs from scheduling code

- nessie/jobs/import_registrations_hist_enr.py
https://jira.ets.berkeley.edu/jira/browse/NS-1155
One more follow-up to #891.
> NS-1155 Logging fix

- config/default.py
- fixtures/ycbm_bookings.json
- nessie/externals/ycbm_api.py
- tests/test_externals/test_ycbm_api.py
https://jira.ets.berkeley.edu/jira/browse/NS-1164
Release instructions for Nessie 4.16 updated.
> NS-1164 Client code for YCBM bookings API

- config/default.py
- nessie/api/job_controller.py
- nessie/jobs/import_ycbm_api.py
- nessie/jobs/scheduling.py
- nessie/lib/util.py
https://jira.ets.berkeley.edu/jira/browse/NS-1165
> NS-1165 Job code for YCBM API import

- nessie/jobs/import_ycbm_api.py
https://jira.ets.berkeley.edu/jira/browse/NS-1165
Follow-up to #899.
> NS-1165 Clean up YCBM API feed on the way in

- config/default.py
- nessie/jobs/create_ycbm_schema.py
- nessie/jobs/scheduling.py
- nessie/lib/util.py
- nessie/sql_templates/create_ycbm_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1166
Release instructions updated.
> NS-1166 External Redshift schema for YCBM bookings

- config/default.py
- nessie/lib/util.py
- nessie/sql_templates/create_ycbm_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1167
> NS-1167 Redshift internal schema for YCBM, reconciled to CalNet UIDs

- config/default.py
https://jira.ets.berkeley.edu/jira/browse/NS-1173
> NS-1173 Remove unused Enrollments API configs

- nessie/sql_templates/create_e_i_advising_notes_schema.template.sql
- nessie/sql_templates/index_e_i_advising_notes.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1181
> NS-1181 Add additional columns to E&I notes parsing

- package-lock.json
https://jira.ets.berkeley.edu/jira/browse/NS-1186
> NS-1186: Upgrades prismjs to 1.24

- nessie/sql_templates/create_advisor_schema.template.sql
- nessie/sql_templates/index_advisors.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1176
> NS-1176 Index advisor/dept relationships in RDS

- nessie/sql_templates/index_advisors.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1176
Follow-up to #908.
> NS-1176 Fix RDS syntax

- nessie/sql_templates/create_sis_schema.template.sql
- nessie/sql_templates/update_rds_indexes_sis.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1175
> NS-1175 Source academic hierarchy data from EDL

- README.md
- config/default.py
- config/test.py
- requirements.txt
https://jira.ets.berkeley.edu/jira/browse/NS-1204
Release instructions updated.
Devs will need to make this change in local configs, too. I'll follow up with them.
> NS-1204, upgrade to SQLAlchemy 1.4 (db refs now use change postgresql:// prefix)

- nessie/sql_templates/create_edl_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1201
https://jira.ets.berkeley.edu/jira/browse/NS-1202
> NS-1201 NS-1202 Improved EDL queries for courses and enrollments

- config/default.py
- nessie/jobs/generate_intermediate_tables.py
- nessie/lib/queries.py
- nessie/sql_templates/create_edl_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1203
> NS-1203 Feature-flagged EDL cutover for course and enrollment data

- nessie/jobs/create_edl_schema.py
- nessie/sql_templates/create_edl_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1203
The more resource-intensive feed generation part of the job remains flagged.
> NS-1203 Lift feature flag on EDL schema creation in Redshift

- nessie/sql_templates/create_ycbm_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1200
> NS-1200 Fix hardcoded schema references in YCBM template

- nessie/api/errors.py
- nessie/sql_templates/create_ycbm_schema.template.sql
- tox.ini
https://jira.ets.berkeley.edu/jira/browse/NS-1200
QA version of #919.
> [QA] NS-1200 Fix hardcoded schema references in YCBM template

- nessie/__init__.py
Timing for this patch is not urgent but let's follow protocol.
> [QA] NOJIRA 4.16.1 patch version

- nessie/lib/queries.py
- nessie/sql_templates/create_edl_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1205
https://jira.ets.berkeley.edu/jira/browse/NS-1206
> NS-1205 NS-1206 Intended majors: EDL Redshift table and feature flag

- nessie/lib/queries.py
- requirements.txt
https://jira.ets.berkeley.edu/jira/browse/NS-1211
> NS-1211, EDL-sourced data to fetch historical non-advisees

- nessie/lib/queries.py
https://jira.ets.berkeley.edu/jira/browse/NS-1211
> NS-1211, minor fix in fetch_non_advisees: column is student_id, not sid

- nessie/merged/student_terms.py
- nessie/sql_templates/create_edl_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1219
> NS-1219 Force integer type in EDL enrollment tables

- nessie/sql_templates/create_edl_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1208
> NS-1208: Adds advising notes to EDL schema

- nessie/api/job_controller.py
... not on the first day of the next month.
> NS-1151: fetch piazza monthly on last day of month

- nessie/lib/queries.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4350
> [QA] BOAC-4350: Broaden hist_enr scope to include SIS-EXTENDED students

- nessie/lib/queries.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4350
QA PR #928
> BOAC-4350: Broaden hist_enr scope to include SIS-EXTENDED students

- nessie/jobs/create_sis_terms_schema.py
- tests/test_jobs/test_create_sis_terms_schema.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4176
> BOAC-4176: Waits up to 10 days after term ends to transition

- nessie/sql_templates/create_edl_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1230
> NS-1230: Adds cs_staging schema to CreateEdlSchema job

- nessie/jobs/create_sis_advising_notes_schema.py
- nessie/sql_templates/create_edl_schema.template.sql
- nessie/sql_templates/index_sis_advising_notes.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1210
> NS-1210: Populates RDS sis_advising_notes with EDL data

- nessie/sql_templates/create_edl_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1230
master PR #934
> [QA] NS-1230: Adds cs_staging schema to CreateEdlSchema job

- fixtures/query_advisee_enrollment_drops.csv
- nessie/lib/queries.py
- nessie/merged/student_terms.py
- tests/test_merged/test_student_terms.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4266
> BOAC-4266: Adds drop date to student enrollment term feeds

- nessie/lib/queries.py
- nessie/merged/student_terms.py
https://jira.ets.berkeley.edu/jira/browse/NS-1235
https://jira.ets.berkeley.edu/jira/browse/NS-1236
> NS-1235, NS-1236: Include serializable drop dates for current and former students

- nessie/jobs/create_sis_advising_notes_schema.py
- nessie/sql_templates/index_sis_advising_notes.template.sql
- nessie/sql_templates/index_sis_appointment_advisors.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-4338
Revert the reversions in #683, fixing conflicts along the way.
> BOAC-4338 Restore Nessie-side appointment indexing

- nessie/sql_templates/index_sis_advising_notes.template.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-4338
Reorder some SQL statements that the reverted reversion in #940 got scrambled.
> BOAC-4338 Follow-ups to SIS appt indexing

- nessie/lib/queries.py
https://jira.ets.berkeley.edu/jira/browse/NS-1227
> NS-1227 Round out SIS API non-advisee polling with FORMER-STUDENT

- config/default.py
- nessie/lib/util.py
- nessie/sql_templates/index_advising_notes.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1168
> NS-1168 BOA-readable RDS indexes for YCBM data

- nessie/sql_templates/index_advising_notes.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1242
> NS-1242 Add student SID to YCBM appt RDS index

- nessie/sql_templates/create_edl_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1228
> NS-1228, replicate academic_standing Redshift table using EDL data

- nessie/jobs/generate_merged_student_feeds.py
- nessie/lib/berkeley.py
https://jira.ets.berkeley.edu/jira/browse/NS-1229
Follows PR #948
> NS-1229, populate acadmic_standing (RDS) per EDL feature-flag

- nessie/externals/cal1card_photo_api.py
- nessie/lib/http.py
https://jira.ets.berkeley.edu/jira/browse/NS-1241
> NS-1241 Add timeout handling, tighten to 15 seconds for student photo API

- config/default.py
- nessie/externals/cal1card_photo_api.py
- nessie/jobs/import_student_photos.py
https://jira.ets.berkeley.edu/jira/browse/CLC-7835
> CLC-7835 Configurable throttle, timeout for student photo API

- nessie/sql_templates/create_edl_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1266
> NS-1266 Fix EDL academic standing mappings

- nessie/sql_templates/create_edl_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1258
> NS-1258 We now have a better EDL class table, let's use it

- nessie/sql_templates/create_edl_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1284
> NS-1284 Fix typo in EDL intended major schema

- nessie/sql_templates/create_edl_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1286
> NS-1286, create table: redshift_schema_edl.student_late_drop_eforms

- nessie/sql_templates/create_edl_schema.template.sql
- nessie/sql_templates/index_sis_advising_notes.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1287
Index `created_at` and `updated_at` to adhere to pattern of indexing notes.
> NS-1287, create table student_late_drop_eforms (RDS) in create_sis_advising_notes_schema job

- nessie/sql_templates/create_edl_schema.template.sql
- nessie/sql_templates/index_advising_notes.template.sql
- nessie/sql_templates/index_sis_advising_notes.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1288
Custom primary key.
> NS-1288, create student_late_drop_eforms search index

- nessie/jobs/verify_sis_advising_note_attachments.py
https://jira.ets.berkeley.edu/jira/browse/NS-1285
> NS-1285: Restores workaround for SFTP attachment file name bug

- nessie/sql_templates/create_edl_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1287
I wrongly assumed it was type string.
> NS-1287, conversion to timestamp not needed for timestamp

- nessie/sql_templates/index_sis_advising_notes.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1290
> NS-1290, 'not null' not needed in dblink 'AS' column-set

- nessie/jobs/create_ycbm_schema.py
https://jira.ets.berkeley.edu/jira/browse/NS-1291
Typo in #970.
> NS-1291 Fix typo in CreateYcbmSchema

- nessie/sql_templates/create_edl_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1292
> NS-1292 Stringify ids from EDL Caldap

- nessie/sql_templates/create_edl_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1293
> NS-1293, eforms table primary-key via ROW_NUMBER() OVER (...)

- nessie/sql_templates/create_edl_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1277
> NS-1277 Clean up a handful of graded-section discrepancies in SIS

- nessie/lib/queries.py
https://jira.ets.berkeley.edu/jira/browse/NS-1297
> NS-1297 Bypass undergrads schema when using EDL SIS views

- nessie/jobs/create_terms_schema.py
https://jira.ets.berkeley.edu/jira/browse/NS-1245
> NS-1245, using EDL.student_academic_terms_data makes life easier

- nessie/jobs/create_advisor_schema.py
- nessie/jobs/create_terms_schema.py
https://jira.ets.berkeley.edu/jira/browse/NS-1247
I broke off `import_calnet_attributes()` and `yesterdays_attributes()` as shared logic.
> NS-1247, CreateAdvisorSchema job: if edl then get advisor ids from edl_external.student_advisor_data

- nessie/jobs/import_registrations.py
- nessie/lib/queries.py
https://jira.ets.berkeley.edu/jira/browse/NS-1301
> NS-1301 Tweak flag-dependent behavior in student feed merge

- nessie/merged/student_demographics.py
https://jira.ets.berkeley.edu/jira/browse/NS-1301
> NS-1301 Adjust ethnicity search filter for EDL sourcing

- nessie/jobs/create_advisor_schema.py
https://jira.ets.berkeley.edu/jira/browse/NS-1247
Corresponding EDO db query:
https://github.com/ets-berkeley-edu/junction/blob/master/app/models/edo_oracle/bulk.rb#L330
> NS-1247, proper WHERE clause in edl.student_advisor_data query

- nessie/lib/queries.py
https://jira.ets.berkeley.edu/jira/browse/NS-1301
> NS-1301 More query adjustments per EDL feature flags

- nessie/lib/queries.py
https://jira.ets.berkeley.edu/jira/browse/NS-1305
> NS-1305 Drop date query adjustments for EDL

- nessie/api/analyze_edl_controller.py
- nessie/jobs/abstract/abstract_registrations_job.py
https://jira.ets.berkeley.edu/jira/browse/NS-1307
PR #989 is related.
> NS-1307, key for demographics lookup varies per EDL feature flag

- nessie/lib/queries.py
https://jira.ets.berkeley.edu/jira/browse/NS-1307
GenerateMergedStudentFeeds needs to heal.
> NS-1307, fix intended_majors subquery in get_advisee_student_profile_elements

- nessie/lib/queries.py
https://jira.ets.berkeley.edu/jira/browse/NS-1307
> NS-1307 Fix table references in EDL-flavored intended major query

- nessie/lib/queries.py
https://jira.ets.berkeley.edu/jira/browse/NS-1308
> NS-1308 Restore intended majors from discontinued programs

- nessie/sql_templates/create_edl_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1309
Good catch, QA dept.
> NS-1309, fix instruction_mode ref in edl.student_class_data query

- nessie/sql_templates/create_edl_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1259
> NS-1259 Don't surface cancelled enrollments as drops

- nessie/sql_templates/create_edl_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1259
QA version of #1002.
> [QA] NS-1259 Don't surface cancelled enrollments as drops

- nessie/api/job_controller.py
https://jira.ets.berkeley.edu/jira/browse/NS-1314
> NS-1314 Add CreateYcbmSchema to Nessie job menu

- nessie/merged/sis_profile.py
- tests/test_merged/test_sis_profile.py
https://jira.ets.berkeley.edu/jira/browse/NS-1316
> NS-1316, ignore duplicate intended majors

- nessie/merged/sis_profile.py
- tests/test_merged/test_sis_profile.py
https://jira.ets.berkeley.edu/jira/browse/NS-1316
master PR is #1007
> [QA] NS-1316, ignore duplicate intended majors

- nessie/jobs/generate_merged_student_feeds.py
https://jira.ets.berkeley.edu/jira/browse/NS-1331
> NS-1331, safe for-loop on sis_profile.get('intendedMajors')

- nessie/jobs/generate_merged_student_feeds.py
https://jira.ets.berkeley.edu/jira/browse/NS-1331
master PR is #1009
> [QA] NS-1331, safe for-loop on sis_profile.get('intendedMajors')

- nessie/lib/queries.py
- nessie/sql_templates/create_edl_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1319
> NS-1319 Feature-flagged cutover to EDL term GPA

- nessie/lib/queries.py
https://jira.ets.berkeley.edu/jira/browse/NS-1326
https://jira.ets.berkeley.edu/jira/browse/NS-1327
https://jira.ets.berkeley.edu/jira/browse/NS-1328
> NS-1326 NS-1327 NS-1328 EDL queries for SIS profile components

- nessie/jobs/create_edl_schema.py
- nessie/lib/queries.py
https://jira.ets.berkeley.edu/jira/browse/NS-1329
> NS-1329 Concurrent EDL-sourced profile feed generation

- fixtures/redshift_schema_edl.sql
- nessie/jobs/create_edl_schema.py
- nessie/lib/queries.py
- nessie/sql_templates/create_edl_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1330
Includes removal of many unused tables.
> NS-1330 EDL cutover followup/cleanup

- nessie/jobs/create_edl_schema.py
- nessie/jobs/import_sis_student_api.py
- nessie/jobs/import_sis_student_api_hist_enr.py
- nessie/lib/queries.py
https://jira.ets.berkeley.edu/jira/browse/NS-1330
Adjustments needed because the EDL profile cutover ended up happening in a different place than some of our feature-flag code expects.
> NS-1330 More fun with EDL cutover flags

- nessie/jobs/create_edl_schema.py
https://jira.ets.berkeley.edu/jira/browse/NS-1330
> NS-1330 Fix typo

- nessie/sql_templates/create_edl_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1339
master PR is #1023
> [QA] NS-1339, ext query to populate edl.academic_standing join on calnet.advisees

- nessie/sql_templates/create_edl_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1339
master PR: #1027
> [QA] NS-1339, query to populate edl.academic_standing gets JOIN on self MAX(action_dt) and GROUP BY

- nessie/lib/queries.py
https://jira.ets.berkeley.edu/jira/browse/NS-1343
> NS-1343 Screen out duplicate/irrelevant rows in historical enrollments feed merge

- nessie/sql_templates/create_edl_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1344
With this modified query, we get the drops reported in Jira above.
> NS-1344, ed.student_enrollment_data query: include canceled section if student dropped it

- nessie/sql_templates/create_edl_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1344
master PR: #1030
> [QA] NS-1344, ed.student_enrollment_data query: include canceled section if student dropped it

- nessie/merged/student_terms.py
https://jira.ets.berkeley.edu/jira/browse/NS-1344
BOA will _always_ show drops when rendering past terms.
> NS-1344, include past-term drops even when term has zero enrollments

- nessie/merged/student_terms.py
https://jira.ets.berkeley.edu/jira/browse/NS-1344
master PR is #1032
> [QA] NS-1344, include past-term drops even when term has zero enrollments

- nessie/merged/student_terms.py
https://jira.ets.berkeley.edu/jira/browse/NS-1349
> NS-1349 Enrollment terms require feed structure even when no enrollments present

- nessie/merged/student_terms.py
https://jira.ets.berkeley.edu/jira/browse/NS-1349
QA version of #1035.
> [QA] NS-1349 Enrollment terms require feed structure even when no enrollments present

- nessie/lib/queries.py
https://jira.ets.berkeley.edu/jira/browse/NS-1351
> NS-1351 Fix f-strings in non-EDL queries

- nessie/lib/queries.py
https://jira.ets.berkeley.edu/jira/browse/NS-1351
QA version of #1037.
> [QA] NS-1351 Fix f-strings in non-EDL queries

- nessie/jobs/create_edl_schema.py
- tests/test_jobs/test_create_edl_schema.py
https://jira.ets.berkeley.edu/jira/browse/NS-1346
Also shuffle some of these job steps into a class hierarchy, because lint-py is rightly complaining that the standalone methods are getting too big to keep straight.
> NS-1346 Save memory with pickles in tempfiles

- nessie/externals/redshift.py
- nessie/jobs/create_edl_schema.py
- nessie/lib/db.py
- nessie/lib/queries.py
https://jira.ets.berkeley.edu/jira/browse/NS-1346
> NS-1346 Enable streaming for massive EDL queries

- nessie/lib/queries.py
https://jira.ets.berkeley.edu/jira/browse/NS-1354
> NS-1354, edl.student_academic_plan_data query: what a diff DISTINCT makes

- nessie/lib/queries.py
https://jira.ets.berkeley.edu/jira/browse/NS-1357
> NS-1357, replace hard-coded dev schema ref with lookup method

- nessie/jobs/create_edl_schema.py
https://jira.ets.berkeley.edu/jira/browse/NS-1360
> NS-1360, case matters in JSON key of subPlan feed (EDL)

- nessie/jobs/generate_merged_student_feeds.py
https://jira.ets.berkeley.edu/jira/browse/NS-1363
> NS-1363 term_id='none' provides a slimmer GenerateMergedStudentFeeds

- nessie/sql_templates/update_rds_indexes_student_profiles_hist_enr.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1373
> NS-1373, accomodate degree.awardedDate of ancient history (eg, 1976-06-19)

- nessie/sql_templates/edl_create_advisor_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1376
> NS-1376, adjust regex cuz Haas advisors have sid=[A-Z]+

- nessie/lib/queries.py
- nessie/merged/student_terms.py
- nessie/sql_templates/create_edl_schema.template.sql
https://jira.ets.berkeley.edu/jira/browse/NS-1375
> NS-1375 Deal with multiple careers in EDL term GPAs

- nessie/merged/student_demographics.py
https://jira.ets.berkeley.edu/jira/browse/NS-1377
> NS-1377 Non-destructive ethnicity filter

- nessie/jobs/create_edl_schema.py
https://jira.ets.berkeley.edu/jira/browse/NS-1361
Follows PR #1054
> NS-1361, str(row['matriculation_term_cd']) < '' is always False

- nessie/jobs/create_edl_schema.py
https://jira.ets.berkeley.edu/jira/browse/NS-1371
Degree of academic_career_cd=GRAD wins if admit_term is greater than degree of academic_career_cd=UGRD.
> NS-1371, slurp up academic_career_cd iff student plan.current_admit_term is most recent

- nessie/jobs/create_edl_schema.py
https://jira.ets.berkeley.edu/jira/browse/NS-1361
...or else you get:
```
File "/opt/python/current/app/nessie/lib/berkeley.py", line 253, in term_info_for_sis_term_id
return season_codes[sis_id[3:4]], year
KeyError: 'e'
```
> NS-1361, do not str(None) prior to matriculation_term_cd comparison

- nessie/jobs/generate_boac_analytics.py
https://jira.ets.berkeley.edu/jira/browse/NS-1279
Follow up to #1078.
> NS-1279 Term id is scalar, not array
